"""Stable public API for Gambit."""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("gambit-markets")
except PackageNotFoundError:  # pragma: no cover - source trees are normally installed
    __version__ = "0+unknown"

from gambit._options import black_scholes_price, cdf, d1, d2, delta, gamma, implied_vol, rho, theta, vega
from gambit.account import Account, ContractPNL, df_roundtrip_trade, roundtrip_trades
from gambit.backtest_result import BacktestBundleError, BacktestResult, BacktestTelemetry, StageTelemetry
from gambit.boundaries import BacktestCallbackError
from gambit.calculation import CalculationContext, CalculationMode, MissingDataPolicy
from gambit.configuration import RunConfiguration, RunProvenance, fingerprint_polars_frame, load_run_configuration
from gambit.control_plane import (
    ControlLevel,
    ExposureLimit,
    ExposureLimitResult,
    HierarchicalExposureLimiter,
    RollingTradeBudget,
    TradingMode,
    TradingOverride,
    TradingOverrideBook,
    TradingOverridePolicy,
)
from gambit.covariance_risk import (
    ComponentVolatilityMeasure,
    CovarianceEstimate,
    CovarianceRiskModel,
    DiversificationRatioMeasure,
    PortfolioRiskLimits,
    PortfolioRiskOverlay,
    PortfolioRiskOverlayResult,
    PortfolioVolatilityMeasure,
)
from gambit.currency import FxRateSnapshot, translate_exposures
from gambit.evaluator import Evaluator, compute_return_metrics, display_return_metrics, plot_return_metrics
from gambit.execution_costs import (
    BidAskSpreadSlippage,
    ChargeModel,
    FixedPercentageSlippage,
    NotionalCharge,
    PerOrderCharge,
    PerUnitCharge,
    SlippageModel,
    SquareRootMarketImpact,
)
from gambit.factor_cache import (
    TICK_DTYPE,
    MappedFloat64Column,
    TickBatchLease,
    TickFactorProcessor,
    TickRing,
    factor_node_key,
    read_reference_float64,
    write_reference_float64,
)
from gambit.factor_dag import (
    FactorCacheAdmissionPolicy,
    FactorDagExecution,
    FactorDagTelemetry,
    PolarsFactorDagExecutor,
    PolarsFactorNode,
)
from gambit.factor_identity import FactorColumnSchema, FactorNodeIdentity
from gambit.factor_operations import (
    FactorCacheCalibration,
    FactorCacheFinding,
    FactorCacheInventory,
    FactorCacheNodeInventory,
    calibrate_factor_cache,
    inspect_factor_cache,
)
from gambit.holiday_calendars import Calendar, get_date_from_weekday
from gambit.instruments import AssetClass, InstrumentSpec, Tradability
from gambit.market_data import MarketDataValidationReport, ValidationFinding, ValidationSeverity, validate_market_data
from gambit.optimize import Experiment, Optimizer, OptimizerWorkerError
from gambit.portfolio import Portfolio
from gambit.position_sizing import (
    VaRTargetSizer,
    VaRTargetSizingResult,
    VolatilityTargetSizer,
    VolatilityTargetSizingResult,
)
from gambit.pq_io import df_to_hdf5, hdf5_to_df, hdf5_to_np_arrays, np_arrays_to_hdf5
from gambit.pq_types import (
    Contract,
    ContractGroup,
    LimitOrder,
    MarketOrder,
    Order,
    OrderStatus,
    Price,
    RollOrder,
    RoundTripTrade,
    StopLimitOrder,
    TimeInForce,
    Trade,
    VWAPOrder,
)
from gambit.pq_utils import (
    Paths,
    PQException,
    assert_,
    find_in_subdir,
    get_child_logger,
    get_main_logger,
    has_display,
    np_find_closest,
    set_defaults,
)
from gambit.risk import (
    DecisionStatus,
    InstrumentTradabilityPolicy,
    MaxOrderQuantity,
    MaxPositionQuantity,
    MaxVolumeParticipation,
    OrderDecision,
    PolicyResult,
    RiskContext,
    RiskPolicy,
    decide_order,
)
from gambit.risk_measures import (
    GrossExposureMeasure,
    NetExposureMeasure,
    PriceMeasure,
    RiskMeasure,
    RiskResult,
    ScenarioPnlMeasure,
    calculate_risk,
)
from gambit.risk_reporting import (
    MarketDataPattern,
    MarketDataShock,
    PortfolioRiskReport,
    ShockType,
    StressScenario,
    account_exposures,
    analyze_account_risk,
    attribute_exposure,
    run_stress_scenarios,
)
from gambit.stages import AccountingStage, ExecutionStage, IndicatorStage, RuleStage, SignalStage, StageGraph, StageNode
from gambit.strategy import (
    DateRangeType,
    IndicatorType,
    MarketSimulatorType,
    PriceFunctionType,
    ReturnReporter,
    RuleType,
    SignalType,
    Strategy,
    StrategyContextType,
)
from gambit.strategy_builder import StrategyBuilder
from gambit.strategy_components import (
    BracketOrderEntryRule,
    ClosePositionExitRule,
    PercentOfEquityTradingRule,
    PriceFuncArrayDict,
    PriceFuncArrays,
    PriceFuncDict,
    SimpleMarketSimulator,
    StopReturnExitRule,
    VectorIndicator,
    VectorSignal,
    VWAPCloseRule,
    VWAPEntryRule,
    VWAPMarketSimulator,
    get_contract_price_from_array_dict,
    get_contract_price_from_dict,
)
from gambit.universe import ContractGroupSpec, ContractSpec, ContractUniverse, create_contract_groups
from gambit.var_risk import (
    FittedTailRiskModel,
    PortfolioExpectedShortfallMeasure,
    PortfolioVaRMeasure,
    TailRiskEstimate,
    TailRiskMethod,
    TailRiskModel,
)

__all__ = [
    "__version__",
    "Account",
    "AccountingStage",
    "AssetClass",
    "BacktestBundleError",
    "BacktestCallbackError",
    "BacktestResult",
    "BacktestTelemetry",
    "BidAskSpreadSlippage",
    "BracketOrderEntryRule",
    "CalculationContext",
    "CalculationMode",
    "Calendar",
    "ChargeModel",
    "ClosePositionExitRule",
    "Contract",
    "ContractGroup",
    "ContractGroupSpec",
    "ContractPNL",
    "ContractSpec",
    "ContractUniverse",
    "ControlLevel",
    "ComponentVolatilityMeasure",
    "CovarianceEstimate",
    "CovarianceRiskModel",
    "DateRangeType",
    "DecisionStatus",
    "DiversificationRatioMeasure",
    "EminiFuture",
    "EminiOption",
    "Evaluator",
    "ExecutionStage",
    "Experiment",
    "ExposureLimit",
    "ExposureLimitResult",
    "FixedPercentageSlippage",
    "FittedTailRiskModel",
    "FxRateSnapshot",
    "FactorColumnSchema",
    "FactorCacheAdmissionPolicy",
    "FactorCacheCalibration",
    "FactorCacheFinding",
    "FactorCacheInventory",
    "FactorCacheNodeInventory",
    "FactorDagExecution",
    "FactorDagTelemetry",
    "FactorNodeIdentity",
    "GrossExposureMeasure",
    "HierarchicalExposureLimiter",
    "IndicatorStage",
    "IndicatorType",
    "InstrumentSpec",
    "InstrumentTradabilityPolicy",
    "InteractivePlot",
    "LimitOrder",
    "LineConfig",
    "LineGraphWithDetailDisplay",
    "MappedFloat64Column",
    "MarketDataPattern",
    "MarketDataShock",
    "MarketDataValidationReport",
    "MarketOrder",
    "MarketSimulatorType",
    "MaxOrderQuantity",
    "MaxPositionQuantity",
    "MaxVolumeParticipation",
    "MissingDataPolicy",
    "NetExposureMeasure",
    "NotionalCharge",
    "Optimizer",
    "OptimizerWorkerError",
    "Order",
    "OrderDecision",
    "OrderStatus",
    "PQException",
    "Paths",
    "PerOrderCharge",
    "PerUnitCharge",
    "PercentOfEquityTradingRule",
    "PolicyResult",
    "Portfolio",
    "PolarsFactorDagExecutor",
    "PolarsFactorNode",
    "PortfolioRiskReport",
    "PortfolioRiskLimits",
    "PortfolioRiskOverlay",
    "PortfolioRiskOverlayResult",
    "PortfolioVolatilityMeasure",
    "PortfolioExpectedShortfallMeasure",
    "PortfolioVaRMeasure",
    "Price",
    "PriceFuncArrayDict",
    "PriceFuncArrays",
    "PriceFuncDict",
    "PriceFunctionType",
    "PriceMeasure",
    "RiskContext",
    "RiskMeasure",
    "RiskPolicy",
    "RiskResult",
    "ReturnReporter",
    "RollOrder",
    "RollingTradeBudget",
    "RoundTripTrade",
    "RuleStage",
    "RuleType",
    "RunConfiguration",
    "RunProvenance",
    "ScenarioPnlMeasure",
    "ShockType",
    "SignalStage",
    "SignalType",
    "SimpleMarketSimulator",
    "SlippageModel",
    "SquareRootMarketImpact",
    "StageGraph",
    "StageNode",
    "StageTelemetry",
    "StopLimitOrder",
    "StopReturnExitRule",
    "Strategy",
    "StrategyBuilder",
    "StrategyContextType",
    "StressScenario",
    "TICK_DTYPE",
    "TailRiskEstimate",
    "TailRiskMethod",
    "TailRiskModel",
    "TickFactorProcessor",
    "TickBatchLease",
    "TickRing",
    "TimeInForce",
    "Tradability",
    "Trade",
    "TradingMode",
    "TradingOverride",
    "TradingOverrideBook",
    "TradingOverridePolicy",
    "VWAPCloseRule",
    "VWAPEntryRule",
    "VWAPMarketSimulator",
    "VWAPOrder",
    "ValidationFinding",
    "ValidationSeverity",
    "VaRTargetSizer",
    "VaRTargetSizingResult",
    "VectorIndicator",
    "VectorSignal",
    "VolatilityTargetSizer",
    "VolatilityTargetSizingResult",
    "account_exposures",
    "analyze_account_risk",
    "assert_",
    "attribute_exposure",
    "black_scholes_price",
    "calculate_risk",
    "calibrate_factor_cache",
    "cdf",
    "compute_return_metrics",
    "d1",
    "d2",
    "decide_order",
    "delta",
    "df_roundtrip_trade",
    "df_to_hdf5",
    "display_return_metrics",
    "factor_node_key",
    "find_in_subdir",
    "fingerprint_polars_frame",
    "future_code_to_month",
    "future_code_to_month_number",
    "gamma",
    "get_child_logger",
    "get_contract_price_from_array_dict",
    "get_contract_price_from_dict",
    "get_date_from_weekday",
    "get_future_code",
    "get_main_logger",
    "has_display",
    "hdf5_to_df",
    "hdf5_to_np_arrays",
    "implied_vol",
    "inspect_factor_cache",
    "load_run_configuration",
    "np_arrays_to_hdf5",
    "np_find_closest",
    "plot_return_metrics",
    "read_reference_float64",
    "rho",
    "roundtrip_trades",
    "run_stress_scenarios",
    "set_defaults",
    "theta",
    "translate_exposures",
    "validate_market_data",
    "create_contract_groups",
    "vega",
    "write_reference_float64",
]


def __getattr__(name: str):
    """Load notebook-only plotting classes on first access."""
    if name in {"InteractivePlot", "LineConfig", "LineGraphWithDetailDisplay"}:
        try:
            from gambit import interactive_plot
        except ImportError as exc:
            raise ImportError(f"{name} requires 'gambit-markets[visualization]'") from exc
        return getattr(interactive_plot, name)
    if name in {
        "EminiFuture",
        "EminiOption",
        "future_code_to_month",
        "future_code_to_month_number",
        "get_future_code",
    }:
        try:
            from gambit import markets
        except ImportError as exc:
            raise ImportError(f"{name} requires 'gambit-markets[calendars]'") from exc
        return getattr(markets, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
