# $$_ Lines starting with # $$_* autogenerated by jup_mini. Do not modify these
# $$_code
# $$_ %%checkall
from __future__ import annotations

import math
from collections import defaultdict
from collections.abc import Sequence
from dataclasses import dataclass
from types import SimpleNamespace
from typing import Callable, cast

import numpy as np
import polars as pl
from numpy.typing import NDArray
from sortedcontainers import SortedDict

from gambit.boundaries import timestamp_index, validate_timestamp_grid
from gambit.contract_pnl import ContractPNL, ContractPNLState, find_index_before
from gambit.execution_snapshots import snapshot_trade
from gambit.pq_types import Contract, ContractGroup, RoundTripTrade, Trade
from gambit.pq_utils import assert_
from gambit.trade_reconciliation import df_roundtrip_trade, roundtrip_trades

NAT = np.datetime64("NaT", "ns")

DETAILED_PNL_SCHEMA = {
    "timestamp": pl.Datetime("ns"),
    "contract_group": pl.String,
    "symbol": pl.String,
    "position": pl.Float64,
    "price": pl.Float64,
    "unrealized": pl.Float64,
    "realized": pl.Float64,
    "commission": pl.Float64,
    "fee": pl.Float64,
    "net_pnl": pl.Float64,
}

ACCOUNT_PNL_SCHEMA = {
    "timestamp": pl.Datetime("ns"),
    "position": pl.Float64,
    "unrealized": pl.Float64,
    "realized": pl.Float64,
    "commission": pl.Float64,
    "fee": pl.Float64,
    "net_pnl": pl.Float64,
    "equity": pl.Float64,
}




def _get_calc_timestamps(timestamps: np.ndarray, pnl_calc_time: int) -> np.ndarray:
    time_delta = np.timedelta64(pnl_calc_time, "m")
    dates = np.unique(timestamps.astype("M8[D]"))
    target_timestamps = dates + time_delta
    day_starts: NDArray[np.intp] = np.asarray(np.searchsorted(timestamps, dates), dtype=np.intp)
    target_ends: NDArray[np.intp] = np.asarray(
        np.searchsorted(timestamps, target_timestamps, side="right"), dtype=np.intp
    )
    calc_indices = target_ends[target_ends > day_starts] - 1
    return timestamps[calc_indices]


@dataclass(frozen=True)
class _AccountTradeState:
    contract_states: dict[str, ContractPNLState]
    contracts: dict[str, Contract]
    symbol_pnls: dict[str, ContractPNL]
    group_pnls: dict[str, list[ContractPNL]]
    trades: list[Trade]
    trades_for_date: dict[tuple[str, np.datetime64], list[Trade]]
    pnl: SortedDict


def _validate_contract_groups(contract_groups: object) -> tuple[ContractGroup, ...]:
    if not isinstance(contract_groups, Sequence) or isinstance(contract_groups, (str, bytes)):
        raise TypeError("account contract_groups must be a sequence of ContractGroup objects")
    groups = tuple(contract_groups)
    if not groups:
        raise ValueError("account requires at least one contract group")
    if not all(isinstance(group, ContractGroup) for group in groups):
        raise TypeError("account contract_groups must contain only ContractGroup objects")
    names = [group.name for group in groups]
    if len(set(names)) != len(names):
        raise ValueError("account contract group names must be unique")
    return groups


class Account:
    """An Account calculates pnl for a set of contracts"""

    def __init__(
        self,
        contract_groups: Sequence[ContractGroup],
        timestamps: np.ndarray,
        price_function: Callable[[Contract, np.ndarray, int, SimpleNamespace | None], float],
        strategy_context: SimpleNamespace | None,
        starting_equity: float = 1.0e6,
        pnl_calc_time: int = 15 * 60,
    ) -> None:
        """
        Args:
            contract_groups: Contract groups that we want to compute PNL for
            timestamps: Timestamps that we might compute PNL at
            price_function: Function that returns contract prices used to compute pnl
            strategy_context: This is passed into the price function so we can use current state of strategy to compute prices
            starting_equity: Starting equity in account currency.  Default 1.e6
            pnl_calc_time: Number of minutes past midnight that we should calculate PNL at.  Default 15 * 60, i.e. 3 pm
        """
        if isinstance(starting_equity, bool) or not isinstance(starting_equity, (int, float)):
            raise TypeError("starting_equity must be numeric")
        if not math.isfinite(starting_equity) or starting_equity <= 0:
            raise ValueError("starting_equity must be finite and positive")
        if isinstance(pnl_calc_time, bool) or not isinstance(pnl_calc_time, (int, np.integer)):
            raise TypeError("pnl_calc_time must be an integer number of minutes")
        if not 0 <= pnl_calc_time < 24 * 60:
            raise ValueError("pnl_calc_time must be between 0 and 1439")
        if not callable(price_function):
            raise TypeError("account price_function must be callable")
        validated_contract_groups = _validate_contract_groups(contract_groups)
        validate_timestamp_grid(timestamps, owner="account")
        self.starting_equity = float(starting_equity)
        self._price_function = price_function
        self.strategy_context = strategy_context
        self.contract_groups = validated_contract_groups

        self.timestamps = timestamps.copy()
        self.timestamps.flags.writeable = False
        self.calc_timestamps = _get_calc_timestamps(self.timestamps, pnl_calc_time)

        self.contracts: dict[str, Contract] = {}
        self._trades: list[Trade] = []
        self._trades_for_date: dict[tuple[str, np.datetime64], list[Trade]] = defaultdict(list)
        self._pnl = SortedDict()
        self.symbol_pnls_by_contract_group: dict[str, list[ContractPNL]] = defaultdict(list)

        self.symbol_pnls: dict[str, ContractPNL] = {}

    def symbols(self) -> list[str]:
        return list(self.contracts.keys())

    @property
    def trade_count(self) -> int:
        """Return the number of executions owned by this account."""
        return len(self._trades)

    def _require_configured_group(self, contract_group: ContractGroup) -> None:
        if not any(contract_group is configured for configured in self.contract_groups):
            raise ValueError(f"contract group {contract_group.name!r} is not configured for this account")

    def _add_contract(self, contract: Contract, timestamp: np.datetime64) -> None:
        if contract.symbol in self.symbol_pnls:
            raise ValueError(f"account already contains contract symbol {contract.symbol}: {contract}")
        contract_pnl = ContractPNL(
            contract,
            self.timestamps,
            self._price_function,
            self.strategy_context,
            _timestamps_validated=True,
        )
        self.symbol_pnls[contract.symbol] = contract_pnl
        # For fast lookup in position function
        self.symbol_pnls_by_contract_group[contract.contract_group.name].append(contract_pnl)
        self.contracts[contract.symbol] = contract

    def _snapshot_trade_state(self, symbols: Sequence[str]) -> _AccountTradeState:
        return _AccountTradeState(
            contract_states={
                symbol: self.symbol_pnls[symbol]._snapshot_state()
                for symbol in symbols
                if symbol in self.symbol_pnls
            },
            contracts=self.contracts.copy(),
            symbol_pnls=self.symbol_pnls.copy(),
            group_pnls={name: pnls.copy() for name, pnls in self.symbol_pnls_by_contract_group.items()},
            trades=self._trades.copy(),
            trades_for_date={key: dated_trades.copy() for key, dated_trades in self._trades_for_date.items()},
            pnl=self._pnl.copy(),
        )

    def _restore_trade_state(self, state: _AccountTradeState) -> None:
        for symbol, contract_state in state.contract_states.items():
            state.symbol_pnls[symbol]._restore_state(contract_state)
        self.contracts.clear()
        self.contracts.update(state.contracts)
        self.symbol_pnls.clear()
        self.symbol_pnls.update(state.symbol_pnls)
        self.symbol_pnls_by_contract_group.clear()
        self.symbol_pnls_by_contract_group.update(state.group_pnls)
        self._trades[:] = state.trades
        self._trades_for_date.clear()
        self._trades_for_date.update(state.trades_for_date)
        self._pnl = state.pnl

    def add_trades(self, trades: Sequence[Trade]) -> None:
        for trade in trades:
            if not isinstance(trade, Trade):
                raise TypeError(f"account trades must be Trade objects: {trade!r}")
            timestamp_index(self.timestamps, trade.timestamp, owner="account")
            contract = trade.contract
            if not any(contract.contract_group is group for group in self.contract_groups):
                raise ValueError(
                    f"trade contract {contract.symbol} is outside the account's configured contract groups"
                )
            if contract.contract_group.contracts.get(contract.symbol) is not contract:
                raise ValueError(f"trade contract {contract.symbol} is not registered in its contract group")
            if contract is not trade.order.contract:
                raise ValueError("trade contract does not match its order")

        trades = sorted((snapshot_trade(trade) for trade in trades), key=lambda x: x.timestamp)
        # Break up trades by contract so we can add them in a batch
        trades_by_contract: dict[str, list[Trade]] = defaultdict(list)
        for trade in trades:
            trades_by_contract[trade.contract.symbol].append(trade)

        for symbol, contract_trades in trades_by_contract.items():
            if symbol in self.symbol_pnls:
                self.symbol_pnls[symbol]._validate_trade_chronology(contract_trades)

        state = self._snapshot_trade_state(list(trades_by_contract))

        try:
            for trade in trades:
                if trade.contract.symbol not in self.contracts:
                    self._add_contract(trade.contract, trade.timestamp)

            for symbol, contract_trades in trades_by_contract.items():
                self.symbol_pnls[symbol]._add_trades(contract_trades)

            for trade in trades:
                self._trades_for_date[(trade.contract.symbol, trade.timestamp.astype("M8[D]"))].append(trade)

            self._trades += trades
            if trades:
                first_timestamp = trades[0].timestamp
                for timestamp in list(self._pnl.keys()):
                    if timestamp >= first_timestamp:
                        del self._pnl[timestamp]
        except BaseException:  # account state must roll back on callback failure or interruption before reraising
            self._restore_trade_state(state)
            raise

    def calc(self, timestamp: np.datetime64) -> None:
        """
        Computes P&L and stores it internally for all contracts.

        Args:
            timestamp: timestamp to compute P&L at.  Account remembers the last timestamp it computed P&L up to and will compute P&L
                between these and including timestamp. If there is more than one day between the last index and current index, we will
                include pnl for at the defined pnl_calc_time for those dates as well.
        """
        timestamp_index(self.timestamps, timestamp, owner="account")
        if timestamp in self._pnl:
            return

        prev_idx = find_index_before(self._pnl, timestamp)
        prev_timestamp = None if prev_idx == -1 else self._pnl.peekitem(prev_idx)[0]

        # Find the last timestamp per day that is between the previous index we computed and the current index,
        # so we can compute daily pnl in addition to the current index pnl
        calc_timestamps = self.calc_timestamps
        intermediate_calc_timestamps = calc_timestamps[calc_timestamps <= timestamp]
        if prev_timestamp is not None:
            intermediate_calc_timestamps = intermediate_calc_timestamps[intermediate_calc_timestamps > prev_timestamp]

        if not len(intermediate_calc_timestamps) or intermediate_calc_timestamps[-1] != timestamp:
            intermediate_calc_timestamps = np.append(intermediate_calc_timestamps, timestamp)

        for ts in intermediate_calc_timestamps:
            net_pnl = 0.0
            for symbol_pnl in self.symbol_pnls.values():
                symbol_pnl.calc_net_pnl(ts)
                net_pnl += symbol_pnl.net_pnl(ts)
            self._pnl[ts] = net_pnl

    def position(self, contract_group: ContractGroup, timestamp: np.datetime64) -> float:
        """Returns netted position for a contract_group at a given date in number of contracts or shares."""
        self._require_configured_group(contract_group)
        position = 0.0
        for symbol_pnl in self.symbol_pnls_by_contract_group[contract_group.name]:
            position += symbol_pnl.position(timestamp)
        return position

    def positions(self, contract_group: ContractGroup, timestamp: np.datetime64) -> list[tuple[Contract, float]]:
        """
        Returns all non-zero positions in a contract group
        """
        self._require_configured_group(contract_group)
        positions = []
        for symbol, contract in contract_group.contracts.items():
            if symbol not in self.symbol_pnls:
                continue
            position = self.symbol_pnls[symbol].position(timestamp)
            if not math.isclose(position, 0):
                positions.append((contract, position))
        return positions

    def equity(self, timestamp: np.datetime64) -> float:
        """Returns equity in this account in Account currency.  Will cause calculation if Account has not previously
        calculated up to this date"""
        pnl = self._pnl.get(timestamp)
        if pnl is None:
            self.calc(timestamp)
            pnl = self._pnl[timestamp]
        return self.starting_equity + pnl

    def get_trades_for_date(self, symbol: str, date: np.datetime64) -> list[Trade]:
        ret = self._trades_for_date.get((symbol, date))
        if ret is None:
            return []
        return [snapshot_trade(trade) for trade in ret]

    def trades(
        self,
        contract_group: ContractGroup | None = None,
        start_date: np.datetime64 = NAT,
        end_date: np.datetime64 = NAT,
    ) -> list[Trade]:
        """Returns a list of trades with the given symbol and with trade date between (and including) start date
        and end date if they are specified. If symbol is None trades for all symbols are returned"""
        if contract_group is not None:
            self._require_configured_group(contract_group)
        return [
            snapshot_trade(trade)
            for trade in self._trades
            if (np.isnat(start_date) or trade.timestamp >= start_date)
            and (np.isnat(end_date) or trade.timestamp <= end_date)
            and (contract_group is None or trade.contract.contract_group == contract_group)
        ]

    def roundtrip_trades(
        self,
        contract_group: ContractGroup | None = None,
        start_date: np.datetime64 = NAT,
        end_date: np.datetime64 = NAT,
    ) -> list[RoundTripTrade]:
        """Returns a list of round trip trades with the given symbol and with trade date
        between (and including) start date and end date if they are specified.
        If symbol is None trades for all symbols are returned"""
        if contract_group is not None:
            self._require_configured_group(contract_group)
        trades = self._trades.copy()
        if contract_group is not None:
            trades = [trade for trade in trades if trade.order.contract.contract_group == contract_group]
        if not np.isnat(start_date):
            trades = [trade for trade in trades if trade.timestamp >= start_date]
        if not np.isnat(end_date):
            trades = [trade for trade in trades if trade.timestamp <= end_date]
        return roundtrip_trades(trades)

    def df_pnl(self, contract_groups: Sequence[str] | None = None) -> pl.DataFrame:
        """
        Returns a dataframe with P&L columns broken down by contract group and symbol

        Args:
            contract_group: Return PNL for this contract group.  If None (default), include all contract groups
        """
        if contract_groups is None:
            contract_groups = list(set([contract.contract_group.name for contract in self.contracts.values()]))

        configured_groups = {group.name: group for group in self.contract_groups}
        dfs = []
        for name in contract_groups:
            contract_group = configured_groups.get(name)
            if contract_group is None:
                raise ValueError(f"contract group {name!r} is not configured for this account")
            for symbol, contract in contract_group.contracts.items():
                if symbol not in self.symbol_pnls:
                    continue
                df = self.symbol_pnls[symbol].df()
                if len(df) > 1:
                    net_pnl_diff = np.diff(df["net_pnl"].to_numpy())
                    last_index = np.nonzero(net_pnl_diff)
                    if len(last_index[0]):
                        last_index_: int = int(last_index[0][-1]) + 1
                        df = df.head(last_index_ + 1)
                df = df.with_columns(pl.lit(contract_group.name).alias("contract_group"))
                dfs.append(df)
        if not dfs:
            return pl.DataFrame(schema=DETAILED_PNL_SCHEMA)
        ret_df = pl.concat(dfs)
        return ret_df.sort(["timestamp", "contract_group", "symbol"]).select(
            "timestamp",
            "contract_group",
            "symbol",
            "position",
            "price",
            "unrealized",
            "realized",
            "commission",
            "fee",
            "net_pnl",
        )

    def df_account_pnl(self, contract_group: ContractGroup | None = None) -> pl.DataFrame:
        """
        Returns PNL at the account level.

        Args:
            contract_group: If set, we only return pnl for this contract_group.  Otherwise we return pnl for all contract groups
        """

        if contract_group is not None:
            self._require_configured_group(contract_group)
            symbols = list(contract_group.contracts.keys())
            symbol_pnls = [self.symbol_pnls[symbol] for symbol in symbols if symbol in self.symbol_pnls]
        else:
            symbol_pnls = list(self.symbol_pnls.values())

        timestamps = self.calc_timestamps
        if not len(timestamps):
            return pl.DataFrame(schema=ACCOUNT_PNL_SCHEMA)
        prev_date = self.calc_timestamps[0] - np.timedelta64(1, "D")
        timestamps = np.insert(timestamps, 0, prev_date)
        position: NDArray[np.float64] = np.full(len(timestamps), 0.0, dtype=float)
        realized: NDArray[np.float64] = np.full(len(timestamps), 0.0, dtype=float)
        unrealized: NDArray[np.float64] = np.full(len(timestamps), 0.0, dtype=float)
        fee: NDArray[np.float64] = np.full(len(timestamps), 0.0, dtype=float)
        commission: NDArray[np.float64] = np.full(len(timestamps), 0.0, dtype=float)
        net_pnl: NDArray[np.float64] = np.full(len(timestamps), 0.0, dtype=float)

        for i in range(1, len(timestamps)):
            timestamp = cast(np.datetime64, timestamps[i])
            for symbol_pnl in symbol_pnls:
                _position, _price, _realized, _unrealized, _fee, _commission, _net_pnl = symbol_pnl.pnl(
                    timestamp
                )
                if math.isfinite(_position):
                    position[i] += _position
                if math.isfinite(_realized):
                    realized[i] += _realized
                if math.isfinite(_unrealized):
                    unrealized[i] += _unrealized
                if math.isfinite(_fee):
                    fee[i] += _fee
                if math.isfinite(_commission):
                    commission[i] += _commission
                if math.isfinite(_net_pnl):
                    net_pnl[i] += _net_pnl

        df = pl.DataFrame(
            {
                "timestamp": timestamps.astype("datetime64[ns]"),
                "position": position,
                "unrealized": unrealized,
                "realized": realized,
                "commission": commission,
                "fee": fee,
                "net_pnl": net_pnl,
            }
        )
        return df.with_columns((self.starting_equity + pl.col("net_pnl")).alias("equity")).select(
            "timestamp", "position", "unrealized", "realized", "commission", "fee", "net_pnl", "equity"
        )

    def df_trades(
        self,
        contract_group: ContractGroup | None = None,
        start_date: np.datetime64 = NAT,
        end_date: np.datetime64 = NAT,
    ) -> pl.DataFrame:
        """
        Returns a dataframe of trades

        Args:
            contract_group: Return trades for this contract group. If None (default), include all contract groups
            start_date: Include trades with date greater than or equal to this timestamp.
            end_date: Include trades with date less than or equal to this timestamp.
        """
        trades = self.trades(contract_group, start_date, end_date)
        df = pl.DataFrame(
            {
                "symbol": [trade.contract.symbol for trade in trades],
                "timestamp": np.asarray([trade.timestamp for trade in trades], dtype="datetime64[ns]"),
                "qty": np.asarray([trade.qty for trade in trades], dtype=float),
                "price": np.asarray([trade.price for trade in trades], dtype=float),
                "fee": np.asarray([trade.fee for trade in trades], dtype=float),
                "commission": np.asarray([trade.commission for trade in trades], dtype=float),
                "order_date": np.asarray([trade.order.timestamp for trade in trades], dtype="datetime64[ns]"),
                "order_qty": np.asarray([trade.order.qty for trade in trades], dtype=float),
                "reason_code": [trade.order.reason_code for trade in trades],
                "order_props": [
                    str(trade.order.properties.__dict__) if trade.order.properties.__dict__ else "" for trade in trades
                ],
                "contract_props": [
                    str(trade.contract.properties.__dict__) if trade.contract.properties.__dict__ else ""
                    for trade in trades
                ],
            },
            schema_overrides={
                "symbol": pl.String,
                "timestamp": pl.Datetime("ns"),
                "order_date": pl.Datetime("ns"),
                "reason_code": pl.String,
                "order_props": pl.String,
                "contract_props": pl.String,
            },
        )
        return df.sort(["timestamp", "symbol"])

    def df_roundtrip_trades(
        self,
        contract_group: ContractGroup | None = None,
        start_date: np.datetime64 = NAT,
        end_date: np.datetime64 = NAT,
    ) -> pl.DataFrame:
        """
        Returns a dataframe of round trip trades

        Args:
            contract_group: Return trades for this contract group. If None (default), include all contract groups
            start_date: Include trades with date greater than or equal to this timestamp.
            end_date: Include trades with date less than or equal to this timestamp.
        """
        rt_trades = self.roundtrip_trades(contract_group, start_date, end_date)
        return df_roundtrip_trade(rt_trades)


def test_account():
    from gambit.pq_types import MarketOrder

    def get_close_price(contract, timestamps, idx, strategy_context):
        if contract.symbol == "IBM":
            price = idx + 10.1
        elif contract.symbol == "MSFT":
            price = idx + 15.3
        elif contract.symbol == "AAPL":
            price = idx + 10
        else:
            raise Exception(f"unknown contract: {contract}")
        return price

    ContractGroup.clear_cache()
    Contract.clear_cache()
    ibm_cg = ContractGroup.get("IBM")
    msft_cg = ContractGroup.get("MSFT")

    ibm_contract = Contract.create("IBM", contract_group=ibm_cg)
    msft_contract = Contract.create("MSFT", contract_group=msft_cg)

    timestamps = np.array(
        ["2018-01-01 09:00", "2018-01-02 08:00", "2018-01-02 09:00", "2018-01-05 13:35", "2018-01-05 13:36"],
        dtype="M8[m]",
    )
    trade_1 = Trade(
        ibm_contract,
        MarketOrder(contract=ibm_contract, timestamp=np.datetime64("2018-01-01 09:00"), qty=10),
        np.datetime64("2018-01-02 08:00"),
        10,
        10.1,
        commission=0.01,
    )
    trade_2 = Trade(
        ibm_contract,
        MarketOrder(contract=ibm_contract, timestamp=np.datetime64("2018-01-01 09:00"), qty=-20),
        np.datetime64("2018-01-02 09:00"),
        -20,
        15.1,
        commission=0.02,
    )
    trade_3 = Trade(
        msft_contract,
        MarketOrder(contract=msft_contract, timestamp=timestamps[1], qty=15),
        timestamps[1],
        20,
        13.2,
        commission=0.04,
    )
    trade_4 = Trade(
        msft_contract,
        MarketOrder(contract=msft_contract, timestamp=timestamps[2], qty=20),
        timestamps[2],
        20,
        16.2,
        commission=0.05,
    )
    trade_5 = Trade(
        msft_contract,
        MarketOrder(contract=msft_contract, timestamp=timestamps[2], qty=5),
        timestamps[2],
        5,
        16.21,
        commission=0.03,
    )

    account = Account([ibm_cg, msft_cg], timestamps, get_close_price, None)
    account.add_trades([trade_1, trade_2, trade_3, trade_4, trade_5])
    account.calc(np.datetime64("2018-01-05 13:35"))

    assert_(len(account.df_trades()) == 5)
    assert_(len(account.df_pnl()) == 6)
    assert_(np.allclose(np.array([9.99, 61.96, 79.97, 109.33, 69.97, 154.33]), account.df_pnl().net_pnl.values, rtol=0))
    assert_(np.allclose(np.array([10, 20, -10, 45, -10, 45]), account.df_pnl().position.values, rtol=0))
    assert_(
        np.allclose(
            np.array([1000000.0, 1000000.0, 1000189.3, 1000224.3]), account.df_account_pnl().equity.values, rtol=0
        )
    )


if __name__ == "__main__":
    test_account()
    import doctest

    doctest.testmod(optionflags=doctest.NORMALIZE_WHITESPACE)
# $$_end_code
