# $$_ Lines starting with # $$_* autogenerated by jup_mini. Do not modify these
# $$_code
# $$_ %%checkall
from __future__ import annotations

# import os
# import inspect
import calendar as cal
import datetime

# from types import FrameType
from typing import Any, Union, cast

import dateutil.relativedelta as rd
import numpy as np
import polars as pl

DateTimeType = Union[str, np.datetime64, np.ndarray, datetime.datetime, datetime.date, pl.Series]

_DAY_TICKS = {
    "D": 1, "h": 24, "m": 1440, "s": 86400,
    "ms": 86400000, "us": 86400000000, "ns": 86400000000000,
}


def _polars_datetimes(values: pl.Series) -> np.ndarray:
    """Require an explicit date dtype before converting a Polars column."""
    if values.dtype != pl.Date and not isinstance(values.dtype, pl.Datetime):
        raise TypeError(f"calendar series must have a Polars Date or Datetime dtype, got {values.dtype}")
    return values.to_numpy()


def _as_np_date(val: DateTimeType) -> np.datetime64 | np.ndarray | None:
    """
    Convert a supported scalar or array to NumPy datetime64[D] and remove time information.
    Returns None if the value cannot be converted
    >>> str(_as_np_date(datetime.datetime(2016, 5, 1, 3, 55)))
    '2016-05-01'
    >>> values = pl.Series([datetime.datetime(2015, 1, 1, 5), datetime.datetime(2015, 2, 1, 6)])
    >>> _as_np_date(values).astype(str).tolist()
    ['2015-01-01', '2015-02-01']
    """
    if isinstance(val, np.datetime64):
        return val.astype("M8[D]")
    if isinstance(val, str) or isinstance(val, datetime.date) or isinstance(val, datetime.datetime):
        np_date: np.datetime64 = np.datetime64(val).astype("M8[D]")
        if isinstance(
            np_date.astype(datetime.datetime), int
        ):  # User can pass in a string like 20180101 which gets parsed as a year
            raise Exception(f"invalid date: {val}")
        return np_date
    if isinstance(val, pl.Series):
        return _polars_datetimes(val).astype("M8[D]")
    if isinstance(val, np.ndarray) and np.issubdtype(val.dtype, np.datetime64):
        return val.astype("M8[D]")
    return None


def _normalize_datetime(
    val: DateTimeType,
) -> tuple[np.datetime64 | np.ndarray, np.timedelta64 | np.ndarray]:
    """
    Break up a datetime into numpy date and numpy timedelta.

    Args:
        val: A supported scalar datetime or datetime array.

    >>> date, td = _normalize_datetime(datetime.datetime(2016, 5, 1, 3, 55))
    >>> assert date == np.datetime64('2016-05-01') and td == np.timedelta64(14100000000000,'ns')
    >>> date, td = _normalize_datetime('2016-05-01')
    >>> assert date == np.datetime64('2016-05-01') and td == np.timedelta64(0, 'D')
    >>> values = pl.Series([datetime.datetime(2015, 1, 1, 5), datetime.datetime(2015, 2, 1, 6)])
    >>> dates, tds = _normalize_datetime(values)
    >>> assert (all(dates == np.array(['2015-01-01', '2015-02-01'], dtype='datetime64[D]'))
    ...    and all(tds == np.array([18000000000000, 21600000000000], dtype='timedelta64[ns]')))
    """
    dtime: np.datetime64 | np.ndarray
    if isinstance(val, pl.Series):
        dtime = _polars_datetimes(val)
    elif isinstance(val, np.ndarray) and np.issubdtype(val.dtype, np.datetime64):
        dtime = val
    else:
        dtime = np.datetime64(cast(Any, val))

    unit, step = np.datetime_data(dtime.dtype)
    if unit in _DAY_TICKS:
        # NumPy's cast to days can wrap at the lower nanosecond boundary.
        # Integer division also avoids overflowing the midnight subtraction.
        ticks = np.asarray(dtime).view("i8")
        missing = np.isnat(dtime)
        total = ticks if step == 1 else ticks.astype(object) * step
        days, remainder = np.divmod(total, _DAY_TICKS[unit])
        date_values = np.asarray(np.where(missing, np.iinfo(np.int64).min, days), dtype="i8")
        time_step = step if _DAY_TICKS[unit] % step == 0 else 1
        time_values = np.asarray(
            np.where(missing, np.iinfo(np.int64).min, remainder // time_step), dtype="i8"
        )
        return date_values.view("M8[D]")[()], time_values.view(f"m8[{time_step}{unit}]")[()]

    date: np.datetime64 | np.ndarray = dtime.astype("M8[D]")
    time_delta = cast(np.timedelta64 | np.ndarray, dtime - date)
    return date, time_delta


def _business_day_ordinal(dates: np.datetime64 | np.ndarray, calendar: np.busdaycalendar) -> np.ndarray:
    """An exact business-day index, including for dates near int64 limits."""
    days = np.asarray(dates).view("i8").astype(object)
    # Day zero is Thursday; count weekdays in the partial week before each date.
    prefix = np.concatenate(([0], np.cumsum(np.roll(calendar.weekmask, -3))))
    partial = np.asarray(prefix[np.asarray(days % 7, dtype=int)]).astype(object)
    weekdays = (days // 7) * int(calendar.weekmask.sum()) + partial
    holidays = np.asarray(np.searchsorted(calendar.holidays, dates)).astype(object)
    return np.asarray(weekdays - holidays, dtype=object)


def _normalize(
    start: DateTimeType, end: DateTimeType, include_first: bool, include_last: bool
) -> tuple[np.datetime64, np.datetime64] | tuple[np.ndarray, np.ndarray]:
    """
    Given a start and end date, return a new start and end date, taking into account include_first and include_last flags

    Args:
        start: start date
        end: end_date
        include_first: whether to increment start date by 1
        include_last: whether to increment end date by 1

    Return:
        new start and end dates

    >>> x = np.arange(np.datetime64('2017-01-01'), np.datetime64('2017-01-10'))
    >>> y = x.astype('M8[ns]')
    >>> xcp = x.copy()
    >>> ycp = y.copy()
    >>> _normalize(x, y, False, False) # doctest:+ELLIPSIS +NORMALIZE_WHITESPACE
    (array(...
    >>> bool((x == xcp).all())
    True
    >>> bool((y == ycp).all())
    True
    """
    s = _as_np_date(start)
    e = _as_np_date(end)

    if s is None or e is None:
        raise ValueError("start and end must be supported date values")

    if np.any(s > e):
        raise ValueError("start date must not be after end date")

    if not include_first and s is not None:
        s += np.timedelta64(1, "D")

    if include_last and e is not None:
        e += np.timedelta64(1, "D")

    # Excluding both sides of a one-day interval crosses the normalized
    # endpoints. Represent that valid empty interval as [end, end) so the
    # count and enumeration APIs agree and never report a negative size.
    if isinstance(s, np.ndarray) or isinstance(e, np.ndarray):
        s, e = np.broadcast_arrays(s, e)
        s = np.where(s > e, e, s)
    elif s > e:
        s = e

    return cast(tuple[np.datetime64, np.datetime64] | tuple[np.ndarray, np.ndarray], (s, e))


class Calendar:
    _bus_day_calendars: dict[str, np.busdaycalendar] = {}

    def __init__(self, calendar_name: str) -> None:
        """
        Create a calendar object
        Args:
            calendar_name (str): name of calendar as defined in the pandas_market_calendars package
        """
        if calendar_name not in Calendar._bus_day_calendars:
            try:
                import pandas_market_calendars as mcal
            except ImportError as exc:  # pragma: no cover - exercised in minimal-install CI
                raise ImportError("exchange calendars require 'gambit-markets[calendars]'") from exc
            cal = mcal.get_calendar(calendar_name)
            holidays = cal.holidays()
            _holidays = np.asarray(holidays.holidays, dtype="datetime64[D]")
            Calendar._bus_day_calendars[calendar_name] = np.busdaycalendar(
                weekmask=holidays.weekmask, holidays=_holidays
            )
        self.bus_day_cal = Calendar._bus_day_calendars[calendar_name]

    def is_trading_day(self, dates: DateTimeType) -> bool | np.ndarray:
        """
        Return whether each date is a trading weekday and is not a holiday.
        Trading weekdays come from the selected calendar and can include weekends.

        Args:
            dates: date times to check
        Return:
            Whether this date is a trading day

        >>> import datetime
        >>> eurex = Calendar('EUREX')
        >>> bool(eurex.is_trading_day('2016-12-25'))
        False
        >>> bool(eurex.is_trading_day(datetime.date(2016, 12, 22)))
        True
        >>> nyse = Calendar('NYSE')
        >>> bool(nyse.is_trading_day('2017-04-01')) # Weekend
        False
        >>> nyse.is_trading_day(np.arange('2017-04-01', '2017-04-09', dtype='datetime64[D]')).tolist()
        [False, False, True, True, True, True, True, False]
        """
        normalized = _as_np_date(dates)
        if normalized is None:
            raise ValueError("dates must be supported date values")
        result = np.is_busday(normalized, busdaycal=self.bus_day_cal)
        return result if isinstance(result, np.ndarray) else bool(result)

    def num_trading_days(
        self, start: DateTimeType, end: DateTimeType, include_first: bool = False, include_last: bool = True
    ) -> float | np.ndarray:
        """
        Count trading days using the requested endpoint inclusion flags.

        Scalar inputs return a float. If either input is an array, the result
        is an array with the broadcast shape, including zero-dimensional
        arrays. Missing endpoints produce NaN without modifying the inputs.
        Start dates after their corresponding end dates are rejected.

        Holiday definitions come from the installed calendar adapter; use short
        invariant examples rather than pinning a mutable multi-year vendor count.
        >>> nyse = Calendar('NYSE')
        >>> float(nyse.num_trading_days('2017-07-03', '2017-07-05'))
        1.0
        >>> dates = np.arange(np.datetime64('2013-01-01'),np.datetime64('2013-01-09'), np.timedelta64(1, 'D'))
        >>> increments = np.array([5, 0, 3, 9, 4, 10, 15, 29])
        >>> dates2 = dates + increments
        >>> dates[4] = np.datetime64('NaT')
        >>> dates2[6] = np.datetime64('NaT')
        >>> result = nyse.num_trading_days(dates, dates2)
        >>> np.nan_to_num(result, nan=-1).tolist()
        [3.0, 0.0, 1.0, 5.0, -1.0, 8.0, -1.0, 20.0]
        """
        s_tmp, e_tmp = _normalize(start, end, include_first, include_last)
        # np.busday_count does not like nat dates
        if isinstance(s_tmp, np.ndarray) or isinstance(e_tmp, np.ndarray):
            s_array, e_array = (value.copy() for value in np.broadcast_arrays(s_tmp, e_tmp))
            mask = np.isnat(s_array) | np.isnat(e_array)
            dummy_date = np.datetime64("1900-01-01")
            s_array[mask] = dummy_date
            e_array[mask] = dummy_date
            vector_count = np.asarray(
                np.busday_count(s_array, e_array, busdaycal=self.bus_day_cal), dtype=float
            )
            vector_count[mask] = np.nan
            return vector_count
        else:
            if np.isnat(s_tmp) or np.isnat(e_tmp):
                return np.nan
            scalar_count = np.busday_count(s_tmp, e_tmp, busdaycal=self.bus_day_cal)
            return float(scalar_count)

    def get_trading_days(
        self, start: DateTimeType, end: DateTimeType, include_first: bool = False, include_last: bool = True
    ) -> int | np.ndarray:
        """
        Get back a list of numpy dates that are trading days between the start and end

        >>> nyse = Calendar('NYSE')
        >>> nyse.get_trading_days('2017-07-04', '2017-07-08').astype(str).tolist()
        ['2017-07-05', '2017-07-06', '2017-07-07']
        >>> nyse.get_trading_days(np.datetime64('2017-07-04'), np.datetime64('2017-07-08')).astype(str).tolist()
        ['2017-07-05', '2017-07-06', '2017-07-07']
        """
        s, e = _normalize(start, end, include_first, include_last)
        dates: np.ndarray = np.arange(s, e, dtype="datetime64[D]")
        dates = dates[np.is_busday(dates, busdaycal=self.bus_day_cal)]
        return dates

    def third_friday_of_month(self, month: int, year: int, roll: str = "backward") -> np.datetime64:
        """
        >>> nyse = Calendar('NYSE')
        >>> str(nyse.third_friday_of_month(3, 2017))
        '2017-03-17'
        """
        # From https://stackoverflow.com/questions/18424467/python-third-friday-of-a-month
        FRIDAY = 4
        first_day_of_month = datetime.datetime(year, month, 1)
        first_friday = first_day_of_month + datetime.timedelta(days=((FRIDAY - cal.monthrange(year, month)[0]) + 7) % 7)
        # 4 is friday of week
        third_friday_date = first_friday + datetime.timedelta(days=14)
        third_friday_dt = third_friday_date.date()
        third_friday = self.add_trading_days(third_friday_dt, 0, roll)
        return cast(np.datetime64, third_friday)

    def add_trading_days(
        self, start: DateTimeType, num_days: int | np.ndarray, roll: str = "raise"
    ) -> np.datetime64 | np.ndarray:
        """
        Adds trading days to a start date

        Args:
            start: start datetimes(s)
            num_days: integer number of trading days to add, or an integer array.
                Floats, strings, and booleans are rejected rather than coerced.
            roll: one of 'raise', 'nat', 'forward', 'following', 'backward', 'preceding', 'modifiedfollowing', 'modifiedpreceding' or 'allow'}
                'allow' is a special case in which case, adding 1 day to a holiday will act as if it was not a holiday, and give you the next business day'
                The rest of the values are the same as in the numpy busday_offset function
                From numpy documentation:
                How to treat dates that do not fall on a valid day. The default is ‘raise’.
                'raise' means to raise an exception for an invalid day.
                'nat' means to return a NaT (not-a-time) for an invalid day.
                'forward' and 'following’ mean to take the first valid day later in time.
                'backward' and 'preceding' mean to take the first valid day earlier in time.
                'modifiedfollowing' means to take the first valid day later in time unless it is across a Month boundary,
                in which case to take the first valid day earlier in time.
                'modifiedpreceding' means to take the first valid day earlier in time unless it is across a Month boundary,
                in which case to take the first valid day later in time.
        Return:
            The datetime num_days trading days after start

        Raises:
            OverflowError: the day offset or timestamp exceeds its representable range.

        >>> calendar = Calendar('NYSE')
        >>> str(calendar.add_trading_days(datetime.date(2015, 12, 24), 1))
        '2015-12-28'
        >>> str(calendar.add_trading_days(np.datetime64('2017-04-15'), 0, roll='preceding'))
        '2017-04-13'
        >>> str(calendar.add_trading_days(np.datetime64('2019-02-17 15:25'), 1, roll='allow'))
        '2019-02-19T15:25'
        """
        if np.asarray(num_days).dtype.kind not in {"i", "u"}:
            raise TypeError("num_days must be an integer or an integer array; booleans are not allowed")
        start_date, time_delta = _normalize_datetime(start)
        if roll == "allow":
            # For positive offsets on closed days, count the rolled day as day one.
            offsets = np.asarray(num_days)
            adjustment = ~np.is_busday(start_date, busdaycal=self.bus_day_cal) & (offsets > 0)
            num_days = offsets - adjustment.astype(offsets.dtype)
            roll = "forward"
        base = np.busday_offset(start_date, 0, roll=cast(Any, roll), busdaycal=self.bus_day_cal)
        out = np.busday_offset(start_date, num_days, roll=cast(Any, roll), busdaycal=self.bus_day_cal)
        valid = ~np.isnat(base)
        # busday_count itself can overflow; use exact integers for the inverse check.
        displacement = (
            _business_day_ordinal(out, self.bus_day_cal) - _business_day_ordinal(base, self.bus_day_cal)
        )
        roll_distance = (
            np.asarray(base).view("i8").astype(object) - np.asarray(start_date).view("i8").astype(object)
        )
        # Rolling to an open day cannot cross more than all holidays plus a week.
        if np.any(valid & (np.isnat(out) | (displacement != num_days))) or np.any(
            ~np.isnat(start_date) & (abs(roll_distance) > 7 * (len(self.bus_day_cal.holidays) + 1)) & valid
        ):
            raise OverflowError("trading-day offset exceeds the representable date range")

        unit, step = np.datetime_data(time_delta.dtype)
        ticks = np.asarray(out).view("i8").astype(object) * (_DAY_TICKS[unit] // step)
        ticks = ticks + np.asarray(time_delta).view("i8").astype(object)
        missing = np.isnat(out) | np.isnat(time_delta)
        limit = np.iinfo(np.int64).max
        if np.any(~missing & ((ticks < -limit) | (ticks > limit))):
            raise OverflowError("trading-day offset exceeds the representable timestamp range")
        values = np.asarray(np.where(missing, np.iinfo(np.int64).min, ticks), dtype="i8")
        return values.view(f"M8[{step}{unit}]")[()]


def get_date_from_weekday(weekday: int, year: int, month: int, week: int) -> np.datetime64:
    """
    Return the requested weekday occurrence (Monday = 0) within a month.
    ``week=-1`` is reserved for the final calendar day of the month.
    >>> str(get_date_from_weekday(1, 2019, 10, 4))
    '2019-10-22'
    """
    if weekday not in range(7):
        raise ValueError(f"weekday must be between 0 and 6: {weekday}")
    if week not in {-1, 1, 2, 3, 4, 5}:
        raise ValueError(f"week must be -1 or between 1 and 5: {week}")
    if week == -1:  # Last day of month
        _, last_day = cal.monthrange(year, month)
        return np.datetime64(datetime.datetime(year, month, last_day)).astype("M8[D]")
    first_day_of_month = datetime.datetime(year, month, 1)
    date = first_day_of_month + rd.relativedelta(weeks=week - 1, weekday=weekday)
    if date.month != month:
        raise ValueError(f"weekday {weekday} does not occur 5 times in {year:04d}-{month:02d}")
    return np.datetime64(date).astype("M8[D]")


if __name__ == "__main__":
    import doctest

    doctest.testmod(optionflags=doctest.NORMALIZE_WHITESPACE)
# $$_end_code
