# $$_ Lines starting with # $$_* autogenerated by jup_mini. Do not modify these
# $$_code
# $$_ %%checkall
import datetime
import re

import dateutil.relativedelta as rd
import numpy as np
from dateutil._common import weekday

from gambit.holiday_calendars import Calendar, get_date_from_weekday
from gambit.pq_utils import assert_

FUTURE_CODES_INT = {"F": 1, "G": 2, "H": 3, "J": 4, "K": 5, "M": 6, "N": 7, "Q": 8, "U": 9, "V": 10, "X": 11, "Z": 12}
FUTURES_CODES_INVERTED: dict[int, str] = {v: k for k, v in FUTURE_CODES_INT.items()}
CURRENT_SYMBOL_DECADE = 2020

FUTURE_CODES_STR = {
    "F": "jan",
    "G": "feb",
    "H": "mar",
    "J": "apr",
    "K": "may",
    "M": "jun",
    "N": "jul",
    "Q": "aug",
    "U": "sep",
    "V": "oct",
    "X": "nov",
    "Z": "dec",
}


def future_code_to_month(future_code: str) -> str:
    """
    Given a future code such as "X", return the month abbreviation, such as "nov"

    Args:
        future_code (str): the one letter future code

    >>> future_code_to_month('X')
    'nov'
    """
    assert_(len(future_code) == 1, f"Future code must be a single character: {future_code}")
    if future_code not in FUTURE_CODES_STR:
        raise Exception(f"unknown future code: {future_code}")
    return FUTURE_CODES_STR[future_code]

    if future_code not in FUTURE_CODES_INT:
        raise Exception(f"unknown future code: {future_code}")
    return FUTURE_CODES_INT[future_code]


def future_code_to_month_number(future_code: str) -> int:
    """
    Given a future code such as "X", return the month number (from 1 - 12)

    Args:
        future_code (str): the one letter future code

    >>> future_code_to_month_number('X')
    11
    """
    assert_(len(future_code) == 1, f"Future code must be a single character: {future_code}")
    if future_code not in FUTURE_CODES_INT:
        raise Exception(f"unknown future code: {future_code}")
    return FUTURE_CODES_INT[future_code]


def get_future_code(month: int) -> str:
    """
    Given a month number such as 3 for March, return the future code for it, e.g. H
    >>> get_future_code(3)
    'H'
    """
    return FUTURES_CODES_INVERTED[month]


def _decode_contract_year(year_code: str) -> int:
    """Decode the repository's deterministic one/two-digit year policy."""
    if not year_code.isdigit() or len(year_code) not in {1, 2}:
        raise ValueError(f"contract year must contain one or two digits: {year_code!r}")
    if len(year_code) == 1:
        return CURRENT_SYMBOL_DECADE + int(year_code)
    return 2000 + int(year_code)


def _format_contract_year(year: int) -> str:
    if not 2000 <= year <= 2099:
        raise ValueError(f"contract year is outside the supported 2000-2099 range: {year}")
    if CURRENT_SYMBOL_DECADE <= year < CURRENT_SYMBOL_DECADE + 10:
        return str(year % 10)
    return f"{year % 100:02d}"


def _parse_future_symbol(symbol: str) -> tuple[str, int]:
    match = re.fullmatch(r"ES([FGHJKMNQUVXZ])(\d{1,2})", symbol)
    if match is None:
        raise ValueError(f"invalid E-mini future symbol: {symbol!r}")
    return match.group(1), _decode_contract_year(match.group(2))


class EminiFuture:
    calendar = Calendar("NYSE")

    @staticmethod
    def get_current_symbol(curr_date: datetime.date) -> str:
        """
        >>> assert(EminiFuture.get_current_symbol(datetime.date(2019, 3, 14)) == 'ESH9')
        >>> assert(EminiFuture.get_current_symbol(datetime.date(2019, 3, 15)) == 'ESM9')
        >>> assert(EminiFuture.get_current_symbol(datetime.date(2020, 3, 14)) == 'ESH0')
        """
        year = curr_date.year
        month = curr_date.month
        day = curr_date.day
        third_friday_ = EminiFuture.calendar.third_friday_of_month(month, year)
        third_friday: datetime.date = third_friday_.astype(datetime.date)
        if month < 3 or (month == 3 and day < third_friday.day):
            month_str = "H"
        elif month < 6 or (month == 6 and day < third_friday.day):
            month_str = "M"
        elif month < 9 or (month == 9 and day < third_friday.day):
            month_str = "U"
        elif month < 12 or (month == 12 and day < third_friday.day):
            month_str = "Z"
        else:
            month_str = "H"
            year += 1
        return "ES" + month_str + _format_contract_year(year)

    @staticmethod
    def get_previous_symbol(curr_future_symbol: str) -> str:
        """
        >>> assert(EminiFuture.get_previous_symbol('ESH9') == 'ESZ8')
        """
        month, year = _parse_future_symbol(curr_future_symbol)
        prev_month = {"H": "Z", "M": "H", "U": "M", "Z": "U"}[month]
        prev_year = year if prev_month != "Z" else year - 1
        return f"ES{prev_month}{_format_contract_year(prev_year)}"

    @staticmethod
    def get_next_symbol(curr_future_symbol: str) -> str:
        """
        >>> assert(EminiFuture.get_next_symbol('ESZ8') == 'ESH9')
        """
        month, year = _parse_future_symbol(curr_future_symbol)
        next_month = {"Z": "H", "H": "M", "M": "U", "U": "Z"}[month]
        next_year = year if next_month != "H" else year + 1
        return f"ES{next_month}{_format_contract_year(next_year)}"

    @staticmethod
    def get_expiry(fut_symbol: str) -> np.datetime64:
        """
        >>> assert(EminiFuture.get_expiry('ESH18') == np.datetime64('2018-03-16T08:30'))
        >>> assert(EminiFuture.get_expiry('ESZ6') == np.datetime64('2026-12-18T08:30'))
        """
        month_str, year = _parse_future_symbol(fut_symbol)
        month = future_code_to_month_number(month_str)
        assert_(isinstance(month, int))
        expiry_date: datetime.date = EminiFuture.calendar.third_friday_of_month(month, year).astype(datetime.date)
        return np.datetime64(expiry_date) + np.timedelta64(8 * 60 + 30, "m")


class EminiOption:
    calendar = Calendar("NYSE")

    @staticmethod
    def decode_symbol(name: str) -> tuple[weekday, int, int, int]:
        """
        >>> EminiOption.decode_symbol('E1AF18')
        (MO, 2018, 1, 1)
        """
        if match := re.fullmatch(r"EW([1-4])([FGHJKMNQUVXZ])(\d{1,2})", name):  # Friday
            week = int(match.group(1))
            month = future_code_to_month_number(match.group(2))
            year = _decode_contract_year(match.group(3))
            return rd.FR, year, month, week
        if match := re.fullmatch(r"E([1-5])A([FGHJKMNQUVXZ])(\d{1,2})", name):  # Monday
            week = int(match.group(1))
            month = future_code_to_month_number(match.group(2))
            year = _decode_contract_year(match.group(3))
            return rd.MO, year, month, week
        if match := re.fullmatch(r"E([1-5])C([FGHJKMNQUVXZ])(\d{1,2})", name):  # Wednesday
            week = int(match.group(1))
            month = future_code_to_month_number(match.group(2))
            year = _decode_contract_year(match.group(3))
            return rd.WE, year, month, week
        if match := re.fullmatch(r"EW([FGHJKMNQUVXZ])(\d{1,2})", name):  # End of month
            week = -1
            month = future_code_to_month_number(match.group(1))
            year = _decode_contract_year(match.group(2))
            return rd.WE, year, month, week
        else:
            raise Exception(f"could not decode: {name}")

    @staticmethod
    def get_expiry(symbol: str) -> np.datetime64:
        """
        >>> EminiOption.get_expiry('EW2Z15')
        numpy.datetime64('2015-12-11T15:00')
        >>> EminiOption.get_expiry('E3AF17')
        numpy.datetime64('2017-01-17T15:00')
        >>> EminiOption.get_expiry('EWF0')
        numpy.datetime64('2020-01-31T15:00')
        """
        assert_(":" not in symbol, f"{symbol} contains: pass in option root instead")
        weekday, year, month, week = EminiOption.decode_symbol(symbol)
        expiry_ = get_date_from_weekday(weekday.weekday, year, month, week)
        if weekday in [rd.WE, rd.FR]:
            expiry = EminiOption.calendar.add_trading_days(expiry_, num_days=0, roll="backward")
        else:
            expiry = EminiOption.calendar.add_trading_days(expiry_, num_days=0, roll="forward")
        # Option expirations changed on 9/20/2015 from 3:15 to 3 pm -
        # See https://www.cmegroup.com/market-regulation/files/15-384.pdf
        expiry += np.where(
            expiry < np.datetime64("2015-09-20"), np.timedelta64(15 * 60 + 15, "m"), np.timedelta64(15, "h")
        )
        if not isinstance(expiry, np.datetime64):
            raise TypeError(f"option expiry calculation returned {type(expiry).__name__}")
        return expiry


if __name__ == "__main__":
    import doctest

    doctest.testmod(optionflags=doctest.NORMALIZE_WHITESPACE)
# $$_end_code
