# $$_ Lines starting with # $$_* autogenerated by jup_mini. Do not modify these
# $$_code
# $$_ %%checkall
from __future__ import annotations

from collections.abc import Sequence
from functools import reduce
from typing import Any, cast

import numpy as np
import polars as pl

from gambit.boundaries import validate_date_range
from gambit.evaluator import compute_return_metrics, display_return_metrics, plot_return_metrics
from gambit.pq_utils import get_child_logger
from gambit.strategy import Strategy

_logger = get_child_logger(__name__)

NAT = np.datetime64("NaT", "ns")


class Portfolio:
    """A portfolio contains one or more strategies that run concurrently so you can test running strategies that are uncorrelated together."""

    def __init__(self, name: str = "main") -> None:
        """Args:
        name: String used for displaying this portfolio
        """
        self.name = name
        self.strategies: dict[str, Strategy] = {}

    def add_strategy(self, name: str, strategy: Strategy) -> None:
        """
        Args:
            name: Name of the strategy
            strategy: Strategy instance
        """
        if not isinstance(name, str) or not name:
            raise ValueError("portfolio strategy name must be a non-empty string")
        if name in self.strategies:
            raise ValueError(f"portfolio strategy {name!r} is already registered")
        if not isinstance(strategy, Strategy):
            raise TypeError("portfolio strategy must be a Strategy")
        if any(strategy is registered for registered in self.strategies.values()):
            raise ValueError("strategy instance is already registered in this portfolio")
        self.strategies[name] = strategy
        strategy.name = name

    def _selected_strategies(self, strategy_names: Sequence[str] | None) -> tuple[Strategy, ...]:
        if strategy_names is None:
            strategy_names = tuple(self.strategies)
        if isinstance(strategy_names, (str, bytes)) or not isinstance(strategy_names, Sequence):
            raise TypeError("portfolio strategy_names must be a sequence of strings")
        if not strategy_names:
            raise ValueError("a portfolio operation requires at least one strategy")
        if not all(isinstance(name, str) for name in strategy_names):
            raise TypeError("portfolio strategy_names must contain only strings")
        unknown = [name for name in strategy_names if name not in self.strategies]
        if unknown:
            raise ValueError(f"unknown portfolio strategies: {', '.join(unknown)}")
        return tuple(self.strategies[name] for name in dict.fromkeys(strategy_names))

    def run_indicators(self, strategy_names: Sequence[str] | None = None) -> None:
        """Compute indicators for the strategies specified

        Args:
            strategy_names: By default this is set to None and we use all strategies.
        """
        for strategy in self._selected_strategies(strategy_names):
            _logger.info(f"running strategy indicators: {strategy.name}")
            strategy.run_indicators()

    def run_signals(self, strategy_names: Sequence[str] | None = None) -> None:
        """Compute signals for the strategies specified.  Must be called after run_indicators

        Args:
            strategy_names: By default this is set to None and we use all strategies.
        """
        for strategy in self._selected_strategies(strategy_names):
            _logger.info(f"running signals: {strategy.name}")
            strategy.run_signals()

    def _generate_order_iterations(
        self,
        strategies: Sequence[Strategy] | None,
        start_date: np.datetime64 = NAT,
        end_date: np.datetime64 = NAT,
    ) -> tuple[np.ndarray, Sequence[tuple[Strategy, np.ndarray]]]:
        """
        >>> class Strategy:
        ...    def __init__(self, num):
        ...        self.timestamps = [
        ...            np.array(['2018-01-01', '2018-01-02', '2018-01-03'], dtype='M8[D]'),
        ...            np.array(['2018-01-02', '2018-01-03', '2018-01-04'], dtype='M8[D]')][num]
        ...        self.num = num
        ...    def _generate_order_iterations(self, start_date, end_date):
        ...        pass
        ...    def __repr__(self):
        ...        return f'{self.num}'
        >>> all_timestamps, orders_iter = Portfolio._generate_order_iterations(None, [Strategy(0), Strategy(1)])
        >>> assert(all(all_timestamps == np.array(['2018-01-01', '2018-01-02', '2018-01-03','2018-01-04'], dtype = 'M8[D]')))
        >>> assert(all(orders_iter[0][1] == np.array([0, 1, 2, 3])))
        >>> assert(all(orders_iter[1][1] == np.array([0, 0, 1, 2])))
        """
        start_date, end_date = validate_date_range(start_date, end_date, owner="portfolio rule execution")
        if strategies is None:
            strategies = tuple(self.strategies.values())

        timestamps_list = [strategy.timestamps for strategy in strategies]

        all_timestamps = np.array(reduce(np.union1d, timestamps_list))

        if not np.isnat(start_date):
            all_timestamps = all_timestamps[(all_timestamps >= start_date)]
        if not np.isnat(end_date):
            all_timestamps = all_timestamps[(all_timestamps <= end_date)]

        iterations: list[tuple[Strategy, np.ndarray]] = []

        for strategy in strategies:
            indices = np.asarray(np.searchsorted(strategy.timestamps, all_timestamps))
            iterations.append((strategy, indices))
            strategy._generate_order_iterations(start_date=start_date, end_date=end_date)

        return all_timestamps, iterations

    def run_rules(
        self,
        strategy_names: Sequence[str] | None = None,
        start_date: np.datetime64 = NAT,
        end_date: np.datetime64 = NAT,
    ) -> None:
        """Run rules for the strategies specified.  Must be called after run_indicators and run_signals.
        See run function for argument descriptions
        """
        strategies = self._selected_strategies(strategy_names)
        start_date, end_date = validate_date_range(start_date, end_date, owner="portfolio rule execution")
        for strategy in strategies:
            strategy.validate_stage_graph()

        _logger.info(f"generating order iterations: {start_date} {end_date}")

        all_timestamps, iterations = self._generate_order_iterations(strategies, start_date, end_date)

        for i, timestamp in enumerate(all_timestamps):
            for strategy, indices in iterations:
                # index into strategy timestamps
                idx = indices[i]
                if idx != len(strategy.timestamps) and strategy.timestamps[idx] == timestamp:
                    strategy._run_iteration(int(idx))

        # Make sure we calc to the end for each strategy
        for strategy in strategies:
            strategy.account.calc(cast(np.datetime64, strategy.timestamps[-1]))

    def run(
        self,
        strategy_names: Sequence[str] | None = None,
        start_date: np.datetime64 = NAT,
        end_date: np.datetime64 = NAT,
    ) -> None:
        """
        Run indicators, signals and rules.

        Args:
            strategy_names: A list of strategy names.  By default this is set to None and we use all strategies.
            start_date: Run rules starting from this date.
              Sometimes we have a few strategies in a portfolio that need different lead times before they are ready to trade
              so you can set this so they are all ready by this date.  Default None
            end_date: Don't run rules after this date.  Default None
        """
        strategies = self._selected_strategies(strategy_names)
        for strategy in strategies:
            strategy.validate_stage_graph()
        selected_names = tuple(strategy.name for strategy in strategies)
        self.run_indicators(selected_names)
        self.run_signals(selected_names)
        self.run_rules(selected_names, start_date, end_date)

    def df_returns(self, sampling_frequency: str = "D", strategy_names: Sequence[str] | None = None) -> pl.DataFrame:
        """
        Return dataframe containing equity and returns with a date index.  Equity and returns are combined from all strategies passed in.

        Args:
            sampling_frequency: Date frequency for rows.  Default 'D' for daily so we will have one row per day
            strategy_names: By default this is set to None and we use all strategies.
        """
        strategies = self._selected_strategies(strategy_names)
        equity_list = []
        selected_names = [strategy.name for strategy in strategies]
        for strategy in strategies:
            equity = strategy.df_returns(sampling_frequency=sampling_frequency)[["timestamp", "equity"]]
            equity = equity.rename({"equity": strategy.name})
            equity_list.append(equity)
        df = reduce(lambda left, right: left.join(right, on="timestamp", how="full", coalesce=True), equity_list)
        return df.with_columns(pl.sum_horizontal(selected_names).alias("equity")).with_columns(
            pl.col("equity").pct_change().alias("ret")
        )

    def evaluate_returns(
        self,
        sampling_frequency: str = "D",
        strategy_names: Sequence[str] | None = None,
        plot: bool = True,
        float_precision: int = 4,
    ) -> dict[Any, Any]:
        """Returns a dictionary of common return metrics.

        Args:
            sampling_frequency: Date frequency.  Default 'D' for daily so we downsample to daily returns before computing metrics
            strategy_names: By default this is set to None and we use all strategies.
            plot: If set to True, display plots of equity, drawdowns and returns.  Default False
            float_precision: Number of significant figures to show in returns.  Default 4
        """
        returns = self.df_returns(sampling_frequency, strategy_names)
        ev = compute_return_metrics(
            returns["timestamp"].to_numpy(), returns["ret"].to_numpy(), returns["equity"][0]
        )
        display_return_metrics(ev.metrics(), float_precision=float_precision)
        if plot:
            plot_return_metrics(ev.metrics())
        return ev.metrics()

    def plot(self, sampling_frequency: str = "D", strategy_names: Sequence[str] | None = None) -> None:
        """Display plots of equity, drawdowns and returns

        Args:
            sampling_frequency: Date frequency.  Default 'D' for daily so we downsample to daily returns before computing metrics
            strategy_names: A list of strategy names.  By default this is set to None and we use all strategies.
        """
        returns = self.df_returns(sampling_frequency, strategy_names)
        timestamps = returns["timestamp"].to_numpy()
        ev = compute_return_metrics(timestamps, returns["ret"].to_numpy(), returns["equity"][0])
        plot_return_metrics(ev.metrics())

    def __repr__(self) -> str:
        return f"{self.name} {self.strategies.keys()}"


if __name__ == "__main__":
    import doctest

    doctest.testmod(optionflags=doctest.NORMALIZE_WHITESPACE)
# $$_end_code
