# $$_ Lines starting with # $$_* autogenerated by jup_mini. Do not modify these
# $$_code
# $$_ %%checkall
from __future__ import annotations

import datetime
import json
import math
import os
import string
from typing import Any

import numpy as np
import polars as pl

from gambit.pq_utils import assert_, get_child_logger, get_temp_dir

_logger = get_child_logger(__name__)

HDF5_FORMAT = "gambit.dataframe"
HDF5_SCHEMA_VERSION = 1
DEFAULT_MAX_HDF5_COLUMNS = 10_000
DEFAULT_MAX_HDF5_ROWS = 100_000_000
DEFAULT_MAX_HDF5_BYTES = 8 * 1024**3

try:
    import h5py as _h5py
except ImportError:  # pragma: no cover - exercised in minimal-install CI
    _h5py = None

h5py: Any = _h5py


def _require_h5py() -> None:
    if h5py is None:
        raise ImportError("HDF5 persistence requires 'gambit-markets[persistence]'")


def _normalize_hdf5_key(key: str) -> str:
    if not isinstance(key, str) or not key.strip("/"):
        raise ValueError("HDF5 key must be a non-empty path")
    parts = key.strip("/").split("/")
    if any(not part or part in {".", ".."} or part.endswith((".__gambit_pending", ".__gambit_backup")) for part in parts):
        raise ValueError(f"invalid HDF5 key: {key!r}")
    return "/".join(parts)


def _validate_resource_limits(max_columns: int, max_rows: int, max_bytes: int) -> None:
    limits = (max_columns, max_rows, max_bytes)
    if any(isinstance(limit, bool) or not isinstance(limit, int) or limit <= 0 for limit in limits):
        raise ValueError("HDF5 resource limits must be positive integers")


def _validate_hdf5_arrays(
    data: dict[str, np.ndarray], *, max_columns: int, max_rows: int, max_bytes: int
) -> int:
    if not isinstance(data, dict):
        raise TypeError("HDF5 data must be a dictionary of NumPy arrays")
    if len(data) > max_columns:
        raise ValueError(f"HDF5 column count exceeds limit of {max_columns}")
    row_count: int | None = None
    total_bytes = 0
    for name, array in data.items():
        if not isinstance(name, str) or not name or "/" in name or name in {".", ".."}:
            raise ValueError(f"invalid HDF5 column name: {name!r}")
        if not isinstance(array, np.ndarray):
            raise TypeError(f"HDF5 column {name} must be a NumPy array")
        if array.ndim != 1:
            raise ValueError(f"HDF5 column {name} must be one-dimensional")
        if row_count is None:
            row_count = len(array)
        elif len(array) != row_count:
            raise ValueError("all HDF5 columns must have the same row count")
        if array.dtype.kind == "O":
            total_bytes += sum(len(str(value).encode("utf-8")) for value in array)
        else:
            total_bytes += array.nbytes
    rows = row_count or 0
    if rows > max_rows:
        raise ValueError(f"HDF5 row count exceeds limit of {max_rows}")
    if total_bytes > max_bytes:
        raise ValueError(f"HDF5 input size exceeds limit of {max_bytes} bytes")
    return rows


def _recover_hdf5_group(file, key: str) -> None:
    pending_key = key + ".__gambit_pending"
    backup_key = key + ".__gambit_backup"
    if key not in file and backup_key in file:
        file.move(backup_key, key)
        file.flush()
    if pending_key in file:
        del file[pending_key]
    if key in file and backup_key in file:
        del file[backup_key]
    file.flush()


def np_arrays_to_hdf5(
    data: dict[str, np.ndarray],
    filename: str,
    key: str,
    dtypes: dict[str, str] | None = None,
    as_utf8: list[str] | None = None,
    compression_args: dict[Any, Any] | None = None,
    *,
    max_columns: int = DEFAULT_MAX_HDF5_COLUMNS,
    max_rows: int = DEFAULT_MAX_HDF5_ROWS,
    max_bytes: int = DEFAULT_MAX_HDF5_BYTES,
) -> None:
    """
    Write a list of numpy arrays to hdf5
    Args:
        data: list of numpy one dimensional arrays along with the name of the array
        filename: filename of the hdf5 file
        key: group and or / subgroups to write to.  For example, "g1/g2" will write to the subgrp g2 within the grp g1
        dtypes: dict used to override datatype for a column.  For example, {"col1": "f4"} will write a 4 byte float array for col1
        as_utf_8: each column listed here will be saved with utf8 encoding. For all other strings, we will compute the max length
        and store as a fixed length byte array with ascii encoding, i.e. a S[max length] datatype. This is much faster to read and process
        compression_args: if you want to compress the hdf5 file. You can use the hdf5plugin module and arguments such as hdf5plugin.Blosc()
    """
    _require_h5py()
    key = _normalize_hdf5_key(key)
    _validate_resource_limits(max_columns, max_rows, max_bytes)
    row_count = _validate_hdf5_arrays(
        data, max_columns=max_columns, max_rows=max_rows, max_bytes=max_bytes
    )
    if not len(data):
        return
    pending_key = key + ".__gambit_pending"
    backup_key = key + ".__gambit_backup"

    if compression_args is None:
        compression_args = {}

    if as_utf8 is None:
        as_utf8 = []
    unknown_utf8 = set(as_utf8) - set(data)
    if unknown_utf8:
        raise ValueError(f"as_utf8 contains unknown columns: {', '.join(sorted(unknown_utf8))}")
    if dtypes is not None:
        unknown_dtypes = set(dtypes) - set(data)
        if unknown_dtypes:
            raise ValueError(f"dtypes contains unknown columns: {', '.join(sorted(unknown_dtypes))}")
    utf8_columns = list(dict.fromkeys(as_utf8))

    with h5py.File(filename, "a") as f:
        _recover_hdf5_group(f, key)
        grp = f.create_group(pending_key)
        try:
            grp.attrs["format"] = HDF5_FORMAT
            grp.attrs["schema_version"] = HDF5_SCHEMA_VERSION
            grp.attrs["state"] = "writing"
            for colname, source_array in data.items():
                array = source_array
                if dtypes is not None and colname in dtypes:
                    dtype: np.dtype[Any] = np.dtype(dtypes[colname])
                    array = array.astype(h5py.opaque_dtype(dtype) if dtype.kind == "M" else dtype)
                else:
                    dtype = array.dtype
                    if colname in utf8_columns or dtype.kind == "U":
                        array = np.char.encode(array.astype("U"), "utf-8")
                        if colname not in utf8_columns:
                            utf8_columns.append(colname)
                    elif dtype.kind == "O":
                        array = np.where(array == None, "", array).astype("S")  # noqa: E711
                    elif dtype.kind == "M":
                        array = array.astype(h5py.opaque_dtype(dtype))
                grp.create_dataset(colname, data=array, shape=[len(array)], dtype=array.dtype, **compression_args)

            grp.attrs["type"] = "dataframe"
            grp.attrs["timestamp"] = datetime.datetime.now(datetime.timezone.utc).isoformat()
            grp.attrs["rows"] = row_count
            grp.attrs["columns_json"] = json.dumps(list(data), separators=(",", ":"))
            grp.attrs["utf8_columns_json"] = json.dumps(utf8_columns, separators=(",", ":"))
            grp.attrs["state"] = "committed"
            f.flush()

            if backup_key in f:
                del f[backup_key]
            if key in f:
                f.move(key, backup_key)
                f.flush()
            f.move(pending_key, key)
            f.flush()
            if backup_key in f:
                del f[backup_key]
            f.flush()
        except BaseException:  # incomplete transactional groups must be removed on interruption before reraising
            if pending_key in f:
                del f[pending_key]
                f.flush()
            raise


def hdf5_to_np_arrays(
    filename: str,
    key: str,
    *,
    max_columns: int = DEFAULT_MAX_HDF5_COLUMNS,
    max_rows: int = DEFAULT_MAX_HDF5_ROWS,
    max_bytes: int = DEFAULT_MAX_HDF5_BYTES,
) -> dict[str, np.ndarray]:
    """
    Read a list of numpy arrays previously written out by np_arrays_to_hdf5
    Args:
        filename: path of the hdf5 file to read
        key: group and or / subgroups to read from.  For example, "g1/g2" will read from the subgrp g2 within the grp g1
    Return:
        a list of numpy arrays along with their names
    """
    _require_h5py()
    key = _normalize_hdf5_key(key)
    _validate_resource_limits(max_columns, max_rows, max_bytes)
    ret: dict[str, np.ndarray] = {}
    with h5py.File(filename, "r") as f:
        read_key = key
        backup_key = key + ".__gambit_backup"
        if read_key not in f and backup_key in f:
            read_key = backup_key
        if read_key not in f:
            _logger.info(f"{key} not found in {filename}")
            return dict()
        grp = f[read_key]
        if "type" not in grp.attrs or grp.attrs["type"] != "dataframe":
            raise ValueError(f"HDF5 group is not a dataframe: {key}")
        if "schema_version" in grp.attrs:
            version = int(grp.attrs["schema_version"])
            if grp.attrs.get("format") != HDF5_FORMAT or version != HDF5_SCHEMA_VERSION:
                raise ValueError(f"unsupported HDF5 dataframe schema version: {version}")
            if grp.attrs.get("state") != "committed":
                raise ValueError(f"HDF5 dataframe group is not committed: {key}")
            columns = json.loads(grp.attrs["columns_json"])
            utf8_cols = json.loads(grp.attrs.get("utf8_columns_json", "[]"))
        else:
            if "columns" not in grp.attrs:
                raise ValueError("legacy HDF5 dataframe is missing its column manifest")
            columns = grp.attrs["columns"].split(",")
            utf8_cols = grp.attrs.get("utf8_cols", "").split(",")
        if (
            not isinstance(columns, list)
            or len(set(columns)) != len(columns)
            or not all(isinstance(column, str) and column for column in columns)
        ):
            raise ValueError("invalid HDF5 dataframe column manifest")
        if not isinstance(utf8_cols, list) or not all(isinstance(column, str) for column in utf8_cols):
            raise ValueError("invalid HDF5 dataframe UTF-8 manifest")
        if set(utf8_cols) - set(columns) - {""}:
            raise ValueError("HDF5 UTF-8 manifest references unknown columns")
        if len(columns) > max_columns:
            raise ValueError(f"HDF5 column count exceeds limit of {max_columns}")
        declared_rows = int(grp.attrs.get("rows", 0))
        if declared_rows < 0 or declared_rows > max_rows:
            raise ValueError(f"HDF5 row count exceeds limit of {max_rows}")
        total_bytes = 0
        for col in columns:
            if col not in grp or not isinstance(grp[col], h5py.Dataset):
                raise ValueError(f"HDF5 dataframe column is missing or invalid: {col}")
            dataset = grp[col]
            if dataset.ndim != 1 or len(dataset) != declared_rows:
                raise ValueError(f"HDF5 dataframe column has inconsistent rows: {col}")
            if dataset.dtype.kind == "O":
                raise ValueError(f"variable-length HDF5 columns are not supported: {col}")
            total_bytes += math.prod(dataset.shape) * dataset.dtype.itemsize
            if total_bytes > max_bytes:
                raise ValueError(f"HDF5 dataset size exceeds limit of {max_bytes} bytes")
            array = dataset[:]
            if col in utf8_cols:
                array = np.char.decode(array, "utf-8")
                dtype = f"U{array.dtype.itemsize}"
            if array.dtype.kind == "S":
                # decode bytes to numpy unicode
                dtype = f"U{array.dtype.itemsize}"
                array = array.astype(dtype)
            elif array.dtype == "O":
                array = array.astype("S")
                array = np.char.decode(array, encoding="utf-8")
            ret[col] = array
    return ret


def df_to_hdf5(
    df: pl.DataFrame, filename: str, key: str, dtypes: dict[str, str] | None = None, as_utf8: list[str] | None = None
) -> None:
    """
    Write out a Polars dataframe to HDF5 using the np_arrays_to_hdf5 function.
    """
    arrays: dict[str, np.ndarray] = {}
    for column in df.columns:
        arrays[column] = df[column].to_numpy()
    np_arrays_to_hdf5(arrays, filename, key, dtypes, as_utf8)


def hdf5_to_df(filename: str, key: str) -> pl.DataFrame:
    """
    Read a Polars dataframe previously written with df_to_hdf5 or np_arrays_to_hdf5.
    """
    arrays = hdf5_to_np_arrays(filename, key)
    if not len(arrays):
        return pl.DataFrame()
    array_dict = {name: array for name, array in arrays.items()}
    return pl.DataFrame(array_dict)


def hdf5_repack(in_filename: str, out_filename: str) -> None:
    """
    Copy groups from input filename to output filename.
    Serves the same purpose as the h5repack command line tool, i.e.
    discards empty space in the input file so the output file may be smaller
    """
    _require_h5py()
    with h5py.File(in_filename, "r") as inf:
        num_items = len(list(inf.keys()))
        with h5py.File(out_filename + ".tmp", "w") as outf:
            for i, name in enumerate(inf):
                _logger.info(f"copying {name} {i} of {num_items}")
                # recursively copies subgroups and datasets
                inf.copy(inf[name], outf)
    os.rename(out_filename + ".tmp", out_filename)


def hdf5_copy(
    in_filename: str, in_key: str, out_filename: str, out_key: str | None = None, skip_if_exists: bool = True
) -> None:
    """
    Recursively copy groups from input filename to output filename.
    Args:
        skip_if_exists: if set, we will skip any groups in the output that already exist.
        Otherwise we replace them.
    >>> tempdir = get_temp_dir()
    >>> in_filename = tempdir + '/temp_in.hdf5'
    >>> out_filename = tempdir + '/temp_out.hdf5'
    >>> for filename in [in_filename, out_filename]:
    ...    if os.path.exists(filename): os.remove(filename)
    >>> key = "test_g/test_subg"
    >>> with h5py.File(in_filename, 'w') as f:
    ...    g = f.create_group(key)
    ...    ds = g.create_dataset('a', data = np.array([5, 3, 2.]))
    >>> hdf5_copy(in_filename, key, out_filename, key)
    >>> with h5py.File(out_filename, 'r') as f:
    ...    assert_(key in f)
    >>> hdf5_copy(in_filename, key, out_filename, key)
    >>> with h5py.File(out_filename, 'r') as f:
    ...    assert_(key in f)
    >>> hdf5_copy(in_filename, key, out_filename, key, False)
    >>> with h5py.File(out_filename, 'r') as f:
    ...    assert_(key in f)

    """
    if out_key is None:
        out_key = in_key
    _require_h5py()
    with h5py.File(in_filename, "r") as inf:
        assert_(in_key in inf, f"could not find {in_key} in {in_filename}")
        with h5py.File(out_filename, "a") as outf:
            if out_key + "_tmp" in outf:
                del outf[out_key + "_tmp"]
            # _logger.info(f'copying {in_key}')
            if out_key in outf:
                if skip_if_exists:
                    # _logger.info(f'{out_key} already exists in {out_filename}, skipping')
                    return
                # _logger.info(f'replacing {out_key} in {out_filename}')
                del outf[out_key]
            outf.copy(inf[in_key], outf, out_key + "_tmp")
            outf.move(out_key + "_tmp", out_key)
            outf.flush()


def test_hdf5_to_df():
    size = int(100)
    a = np.random.randint(0, 10000, size)
    b = a * 1.1
    letters = np.random.choice(list(string.ascii_letters), (size, 5))
    c: np.ndarray = np.empty(size, dtype="O")
    for i, row in enumerate(letters):
        c[i] = "".join(row)
    c[1] = None
    d = (a * 1000).astype("M8[m]")
    temp_dir = get_temp_dir()
    # os.remove(f'{temp_dir}/test.hdf5')
    if os.path.isfile(f"{temp_dir}/test.hdf5"):
        os.remove(f"{temp_dir}/test.hdf5")
    np_arrays_to_hdf5({"b": b, "a": a, "c": c, "d": d}, f"{temp_dir}/test.hdf5", "key1/key2")
    file_size = os.path.getsize(f"{temp_dir}/test.hdf5")
    print(f"file size: {file_size / 1e3:.0f} KB")

    hdf5_repack(f"{temp_dir}/test.hdf5", f"{temp_dir}/test.hdf5.tmp")
    if os.path.isfile(f"{temp_dir}/test.hdf5"):
        os.remove(f"{temp_dir}/test.hdf5")
    os.rename(f"{temp_dir}/test.hdf5.tmp", f"{temp_dir}/test.hdf5")
    file_size = os.path.getsize(f"{temp_dir}/test.hdf5")
    print(f"file size: {file_size / 1e3:.0f} KB")
    assert_(file_size > 10000 and file_size < 14000, f"invalid file size: {file_size}")

    if os.path.isfile(f"{temp_dir}/test.hdf5"):
        os.remove(f"{temp_dir}/test.hdf5")
    df_in = pl.DataFrame(dict(a=a, b=b, c=c, d=d), strict=False)
    df_to_hdf5(df_in, f"{temp_dir}/test.hdf5", "key1/key2", dtypes={"d": "M8[m]"})
    df_out = hdf5_to_df(f"{temp_dir}/test.hdf5", "key1/key2")
    df_out = df_out.with_columns(pl.when(pl.col("c") == "").then(None).otherwise(pl.col("c")).alias("c"))
    assert_(df_in.equals(df_out))


if __name__ == "__main__":
    test_hdf5_to_df()
    import doctest

    doctest.testmod(optionflags=doctest.NORMALIZE_WHITESPACE | doctest.ELLIPSIS)
# $$_end_code
