# $$_ Lines starting with # $$_* autogenerated by jup_mini. Do not modify these
# $$_code
# $$_ %%checkall
from __future__ import annotations

import datetime
import math
import types
from dataclasses import dataclass, field
from enum import Enum
from types import SimpleNamespace
from typing import Any, ClassVar, cast

import numpy as np

from gambit.instruments import InstrumentSpec
from gambit.pq_utils import get_child_logger

_logger = get_child_logger(__name__)


def _python_datetime(value: np.datetime64) -> datetime.datetime:
    """Convert a NumPy timestamp for human-readable representations."""
    return cast(datetime.datetime, value.astype("datetime64[us]").astype(datetime.datetime))


@dataclass
class ContractGroup:
    """A way to group contracts for figuring out which indicators, rules and signals to apply to a contract and for PNL reporting"""

    _instances: ClassVar[dict[str, ContractGroup]] = {}
    name: str
    contracts: dict[str, Contract]

    def __init__(self, name: str) -> None:
        self.name = name
        self.contracts = {}

    @staticmethod
    def get(name: str) -> ContractGroup:
        """
        Create a contract group if it does not exist, or returns an existing one
         Args:
            name: Name of the group
        """
        if not isinstance(name, str) or not name:
            raise ValueError("contract group name must be a non-empty string")
        if name not in ContractGroup._instances:
            cg = ContractGroup(name)
            ContractGroup._instances[name] = cg
            return cg
        return ContractGroup._instances[name]

    @staticmethod
    def get_default() -> ContractGroup:
        return DEFAULT_CG

    @staticmethod
    def exists(name: str) -> bool:
        return name in ContractGroup._instances

    def add_contract(self, contract):
        if contract.symbol not in self.contracts:
            self.contracts[contract.symbol] = contract

    def get_contract(self, symbol: str) -> Contract | None:
        return self.contracts.get(symbol)

    def get_contracts(self) -> list[Contract]:
        return list(self.contracts.values())

    @staticmethod
    def clear_cache() -> None:
        """Remove cached groups and their contract references.

        ``DEFAULT_CG`` is a module-level singleton imported by strategy code, so
        replacing it would leave those imports pointing at stale state. Preserve
        its identity, clear every registered group, and register it as the sole
        fresh group.
        """
        for contract_group in ContractGroup._instances.values():
            contract_group.clear()
        DEFAULT_CG.clear()
        ContractGroup._instances = {DEFAULT_CG.name: DEFAULT_CG}

    def clear(self) -> None:
        """Remove all contracts"""
        self.contracts.clear()

    def __repr__(self) -> str:
        return self.name


DEFAULT_CG = ContractGroup.get("DEFAULT")


def _format(obj: SimpleNamespace | None) -> str:
    if obj is None:
        return ""
    if len(obj.__dict__) == 0:
        return ""
    return str(obj)


@dataclass
class Contract:
    _instances: ClassVar[dict[str, Contract]] = {}
    symbol: str
    contract_group: ContractGroup
    expiry: np.datetime64 | None
    multiplier: float
    components: list[tuple[Contract, float]]
    properties: SimpleNamespace
    instrument_spec: InstrumentSpec

    """A contract such as a stock, option or a future that can be traded"""

    @staticmethod
    def create(
        symbol: str,
        contract_group: ContractGroup | None = None,
        expiry: np.datetime64 | None = None,
        multiplier: float = 1.0,
        components: list[tuple[Contract, float]] | None = None,
        properties: SimpleNamespace | None = None,
        instrument_spec: InstrumentSpec | None = None,
    ) -> "Contract":
        """
        Args:
            symbol: A unique string reprenting this contract. e.g IBM or ESH9
            contract_group: We sometimes need to group contracts for calculating PNL, for example, you may have a strategy
                which has options and a future or equity used to hedge delta.  In this case, you will be trading
                different symbols over time as options and futures expire, but you may want to track PNL for each leg using
                a contract group for each leg. So you could create contract groups 'OPTIONS' and one for 'HEDGES'
            expiry: In the case of a future or option, the date and time when the
                contract expires.  For equities and other non expiring contracts, set this to None.  Default None.
            multiplier: If the market price convention is per unit, and the unit is not the same as contract size,
                set the multiplier here. For example, for E-mini contracts, each contract is 50 units and the price is per unit,
                so multiplier would be 50.  Default 1
            properties: Any data you want to store with this contract.
                For example, you may want to store option strike.  Default None
        """
        if not isinstance(symbol, str) or not symbol:
            raise ValueError("contract symbol must be a non-empty string")
        if contract_group is None:
            contract_group = DEFAULT_CG
        if not isinstance(contract_group, ContractGroup):
            raise TypeError("contract_group must be a ContractGroup")
        if symbol in Contract._instances:
            raise ValueError(f"Contract with symbol: {symbol} already exists")
        multiplier = _finite_real(multiplier, field_name="contract multiplier")
        if multiplier <= 0:
            raise ValueError("contract multiplier must be positive")
        if expiry is not None:
            if not isinstance(expiry, np.datetime64):
                raise TypeError("contract expiry must be a numpy datetime64 value or None")
            if np.isnat(expiry):
                raise ValueError("contract expiry cannot be NaT")
        if components is None:
            components = []
        validated_components: list[tuple[Contract, float]] = []
        for component in components:
            if not isinstance(component, tuple) or len(component) != 2:
                raise TypeError("contract components must be (Contract, ratio) tuples")
            component_contract, ratio = component
            if not isinstance(component_contract, Contract):
                raise TypeError("contract component instruments must be Contract objects")
            ratio = _finite_real(ratio, field_name="contract component ratio")
            if math.isclose(ratio, 0.0):
                raise ValueError("contract component ratios must be nonzero")
            validated_components.append((component_contract, ratio))
        if properties is None:
            properties = types.SimpleNamespace()
        elif not isinstance(properties, SimpleNamespace):
            raise TypeError("contract properties must be a SimpleNamespace or None")
        if instrument_spec is None:
            instrument_spec = InstrumentSpec()
        elif not isinstance(instrument_spec, InstrumentSpec):
            raise TypeError("instrument_spec must be an InstrumentSpec or None")
        contract = Contract(
            symbol,
            contract_group,
            expiry,
            multiplier,
            validated_components,
            properties,
            instrument_spec,
        )
        contract_group.add_contract(contract)
        contract.contract_group = contract_group
        Contract._instances[symbol] = contract
        return contract

    def is_basket(self) -> bool:
        return len(self.components) > 0

    @staticmethod
    def exists(name) -> bool:
        return name in Contract._instances

    @staticmethod
    def get(name) -> Contract | None:
        """
        Returns an existing contrat or none if it does not exist
        """
        return Contract._instances.get(name)

    @staticmethod
    def get_or_create(
        symbol: str,
        contract_group: ContractGroup | None = None,
        expiry: np.datetime64 | None = None,
        multiplier: float = 1.0,
        components: list[tuple[Contract, float]] | None = None,
        properties: SimpleNamespace | None = None,
        instrument_spec: InstrumentSpec | None = None,
    ) -> Contract:
        if symbol in Contract._instances:
            return Contract._instances[symbol]
        return Contract.create(symbol, contract_group, expiry, multiplier, components, properties, instrument_spec)

    @staticmethod
    def clear_cache() -> None:
        """
        Remove the contract cache and every group's references to its contracts.
        """
        for contract_group in ContractGroup._instances.values():
            contract_group.clear()
        Contract._instances = {}

    def __repr__(self) -> str:
        expiry = self.expiry.astype("datetime64[us]").astype(datetime.datetime) if self.expiry is not None else None
        return (
            f"{self.symbol}"
            + (f" {self.multiplier}" if self.multiplier != 1 else "")
            + (f" expiry: {expiry:%Y-%m-%d %H:%M:%S}" if expiry is not None else "")
            + (f" group: {self.contract_group.name}" if self.contract_group else "")
            + (f" {_format(self.properties)}")
        )


@dataclass
class Price:
    """
    >>> price = Price(datetime.datetime(2020, 1, 1), 15.25, 15.75, 189, 300)
    >>> print(price)
    15.25@189/15.75@300
    >>> price.properties = SimpleNamespace(delta = -0.3)
    >>> price.valid = False
    >>> print(price)
    15.25@189/15.75@300 delta: -0.3 invalid
    >>> print(price.mid())
    15.5
    """

    timestamp: datetime.datetime
    bid: float
    ask: float
    bid_size: int
    ask_size: int
    valid: bool = True
    properties: SimpleNamespace | None = None

    @staticmethod
    def invalid() -> Price:
        return Price(
            datetime.datetime(datetime.MINYEAR, 1, 1), bid=math.nan, ask=math.nan, bid_size=-1, ask_size=-1, valid=False
        )

    def mid(self) -> float:
        return 0.5 * (self.bid + self.ask)

    def vw_mid(self) -> float:
        """
        Volume weighted mid
        >>> price = Price(datetime.datetime(2020, 1, 1), 15.25, 15.75, 189, 300)
        >>> print(f'{price.vw_mid():.4f}')
        15.4433
        >>> price.bid_size = 0
        >>> price.ask_size = 0
        >>> assert math.isnan(price.vw_mid())
        """
        if self.bid_size + self.ask_size == 0:
            return math.nan
        return (self.bid * self.ask_size + self.ask * self.bid_size) / (self.bid_size + self.ask_size)

    def set_property(self, name: str, value: Any) -> None:
        if self.properties is None:
            self.properties = SimpleNamespace()
        setattr(self.properties, name, value)

    def spread(self) -> float:
        if self.ask < self.bid:
            return math.nan
        return self.ask - self.bid

    def __repr__(self) -> str:
        msg = f"{self.bid:.2f}@{self.bid_size}/{self.ask:.2f}@{self.ask_size}"
        if self.properties:
            for k, v in self.properties.__dict__.items():
                if isinstance(v, (np.floating, float)):
                    msg += f" {k}: {v:.5g}"
                else:
                    msg += f" {k}: {v}"
        if not self.valid:
            msg += " invalid"
        return msg


class OrderStatus(Enum):
    """
    Enum for order status
    """

    OPEN = 1
    PARTIALLY_FILLED = 2
    FILLED = 3
    CANCEL_REQUESTED = 4
    CANCELLED = 5


class TimeInForce(Enum):
    FOK = 1  # Fill or Kill
    GTC = 2  # Good till Cancelled
    DAY = 3  # Cancel at EOD


def _whole_quantity(value: float, *, field_name: str) -> int:
    if (
        isinstance(value, (bool, np.bool_))
        or not isinstance(value, (int, float, np.integer, np.floating))
        or not np.isfinite(value)
        or math.isclose(float(value), 0)
        or not float(value).is_integer()
    ):
        raise ValueError(f"{field_name} must be finite and nonzero, in whole shares or contracts")
    return int(value)


def _finite_real(value: float, *, field_name: str) -> float:
    if (
        isinstance(value, (bool, np.bool_))
        or not isinstance(value, (int, float, np.integer, np.floating))
        or not np.isfinite(value)
    ):
        raise ValueError(f"{field_name} must be a finite real number")
    return float(value)


@dataclass(kw_only=True)
class Order:
    """
    Args:
        contract: The contract this order is for
        timestamp: Time the order was placed
        qty:  Number of contracts or shares.  Use a negative quantity for sell orders
        reason_code: The reason this order was created. Default ''
        properties: Any order specific data we want to store.  Default None
        status: Status of the order, "open", "filled", etc. Default "open"
    """

    contract: Contract
    timestamp: np.datetime64 = np.datetime64("NaT", "ns")
    qty: float = math.nan
    reason_code: str = ""
    time_in_force: TimeInForce = TimeInForce.FOK
    properties: SimpleNamespace = field(default_factory=SimpleNamespace)
    status: OrderStatus = OrderStatus.OPEN

    def __post_init__(self) -> None:
        if not isinstance(self.contract, Contract):
            raise TypeError("order contract must be a Contract")
        if not isinstance(self.timestamp, np.datetime64):
            raise TypeError("order timestamp must be a numpy datetime64 value")
        if not isinstance(self.time_in_force, TimeInForce):
            raise TypeError("order time_in_force must be a TimeInForce")
        if not isinstance(self.status, OrderStatus):
            raise TypeError("order status must be an OrderStatus")
        self.qty = _whole_quantity(self.qty, field_name="order qty")

    def is_open(self) -> bool:
        return self.status in [OrderStatus.OPEN, OrderStatus.CANCEL_REQUESTED, OrderStatus.PARTIALLY_FILLED]

    def request_cancel(self) -> None:
        if self.status in (OrderStatus.FILLED, OrderStatus.CANCELLED, OrderStatus.CANCEL_REQUESTED):
            return
        self.status = OrderStatus.CANCEL_REQUESTED

    def fill(self, fill_qty: float = math.nan) -> None:
        if self.status not in (OrderStatus.OPEN, OrderStatus.PARTIALLY_FILLED):
            raise ValueError(f"cannot fill an order in status: {self.status}")
        if isinstance(fill_qty, (float, np.floating)) and math.isnan(float(fill_qty)):
            fill_qty = self.qty
        fill_qty = _whole_quantity(fill_qty, field_name="fill qty")
        if self.qty * fill_qty < 0:
            raise ValueError(f"order qty: {self.qty} cannot be opposite sign of {fill_qty}")
        if abs(fill_qty) > abs(self.qty):
            raise ValueError(f"cannot fill qty: {fill_qty} larger than order qty: {self.qty}")
        self.qty -= fill_qty
        if math.isclose(self.qty, 0):
            self.status = OrderStatus.FILLED
        else:
            self.status = OrderStatus.PARTIALLY_FILLED

    def cancel(self) -> None:
        if self.status in (OrderStatus.FILLED, OrderStatus.CANCELLED):
            return
        self.status = OrderStatus.CANCELLED


@dataclass(kw_only=True)
class MarketOrder(Order):
    def __post_init__(self) -> None:
        super().__post_init__()

    def __repr__(self) -> str:
        timestamp = _python_datetime(self.timestamp)
        return " ".join(
            part
            for part in (
                self.contract.symbol,
                f"{timestamp:%Y-%m-%d %H:%M:%S}",
                f"qty: {self.qty}",
                self.reason_code,
                _format(self.properties),
                str(self.status),
            )
            if part
        )


@dataclass(kw_only=True)
class LimitOrder(Order):
    limit_price: float

    def __post_init__(self) -> None:
        super().__post_init__()

    def __repr__(self) -> str:
        timestamp = _python_datetime(self.timestamp)
        symbol = self.contract.symbol if self.contract else ""
        return (
            f"{symbol} {timestamp:%Y-%m-%d %H:%M:%S} qty: {self.qty} lmt_prc: {self.limit_price}"
            f" {self.reason_code} {_format(self.properties)} {self.status}"
        )


@dataclass(kw_only=True)
class RollOrder(Order):
    close_qty: float
    reopen_qty: float

    def __post_init__(self) -> None:
        self.close_qty = _whole_quantity(self.close_qty, field_name="roll close qty")
        self.reopen_qty = _whole_quantity(self.reopen_qty, field_name="roll reopen qty")

    def __repr__(self) -> str:
        timestamp = _python_datetime(self.timestamp)
        symbol = self.contract.symbol if self.contract else ""
        return (
            f"{symbol} {timestamp:%Y-%m-%d %H:%M:%S} close_qty: {self.close_qty} reopen_qty: {self.reopen_qty}"
            f" {self.reason_code} {_format(self.properties)} {self.status}"
        )


@dataclass(kw_only=True)
class StopLimitOrder(Order):
    """Used for stop loss or stop limit orders.  The order is triggered when price goes above or below trigger price, depending on whether this is a short
      or long order.  Becomes either a market or limit order at that point, depending on whether you set the limit price or not.

    Args:
        trigger_price: Order becomes a market or limit order if price crosses trigger_price.
        limit_price: If not set (default), order becomes a market order when price crosses trigger price.
            Otherwise it becomes a limit order.  Default np.nan
    """

    trigger_price: float
    limit_price: float = np.nan
    triggered: bool = False

    def __post_init__(self) -> None:
        super().__post_init__()

    def __repr__(self) -> str:
        timestamp = _python_datetime(self.timestamp)
        symbol = self.contract.symbol if self.contract else ""
        return (
            f"{symbol} {timestamp:%Y-%m-%d %H:%M:%S} qty: {self.qty} trigger_prc: {self.trigger_price} limit_prc: {self.limit_price}"
            f" {self.reason_code} {_format(self.properties)} {self.status}"
        )


@dataclass(kw_only=True)
class VWAPOrder(Order):
    """
    An order type to trade at VWAP. A vwap order executes at VWAP from the point it is sent to the market
    till the vwap end time specified in the order.

    Args:
        vwap_stop: limit price. If market price <= vwap_stop for buys or market price
        >= vwap_stop for sells, the order is executed at that point.
        vwap_end_time: We want to execute at VWAP computed from now to this time
    """

    vwap_stop: float = math.nan
    vwap_end_time: np.datetime64

    def __post_init__(self) -> None:
        super().__post_init__()
        if not isinstance(self.timestamp, np.datetime64) or not isinstance(self.vwap_end_time, np.datetime64):
            raise TypeError("VWAP order timestamps must be numpy datetime64 values")
        if np.isnat(self.timestamp) or np.isnat(self.vwap_end_time):
            raise ValueError("VWAP order timestamps cannot be NaT")
        if self.vwap_end_time < self.timestamp:
            raise ValueError("VWAP end time cannot precede the order timestamp")

    def __repr__(self):
        timestamp = _python_datetime(self.timestamp)
        return (
            f"{self.contract.symbol} {timestamp:%Y-%m-%d %H:%M:%S} "
            f"limit: {self.vwap_stop:.3f} end: {self.vwap_end_time} qty: {self.qty}"
            f" {self.reason_code} {_format(self.properties)} {self.status}"
        )


class Trade:
    def __init__(
        self,
        contract: Contract,
        order: Order,
        timestamp: np.datetime64,
        qty: float,
        price: float,
        fee: float = 0.0,
        commission: float = 0.0,
        properties: SimpleNamespace | None = None,
    ) -> None:
        """
        Args:
            contract: The contract we traded
            order: A reference to the order that created this trade. Default None
            timestamp: Trade execution datetime
            qty: Number of contracts or shares filled
            price: Trade price
            fee: Fees paid to brokers or others. Default 0
            commision: Commission paid to brokers or others. Default 0
            properties: Any data you want to store with this contract.
                For example, you may want to store bid / ask prices at time of trade.  Default None
        """
        if not isinstance(contract, Contract):
            raise TypeError("trade contract must be a Contract")
        if not isinstance(order, Order):
            raise TypeError("trade order must be an Order")
        if contract is not order.contract:
            raise ValueError("trade contract must match its originating order")
        if not isinstance(timestamp, np.datetime64):
            raise TypeError("trade timestamp must be a numpy datetime64 value")
        if np.isnat(timestamp):
            raise ValueError("trade timestamp cannot be NaT")
        if not isinstance(order.timestamp, np.datetime64) or np.isnat(order.timestamp):
            raise ValueError("trade order timestamp must be a valid numpy datetime64 value")
        if timestamp < order.timestamp:
            raise ValueError("trade timestamp cannot precede its originating order")
        qty = _whole_quantity(qty, field_name="trade qty")
        price = _finite_real(price, field_name="trade price")
        fee = _finite_real(fee, field_name="trade fee")
        commission = _finite_real(commission, field_name="trade commission")

        self.contract = contract
        self.order = order
        self.timestamp = timestamp
        self.qty = qty
        self.price = price
        self.fee = fee
        self.commission = commission

        if properties is None:
            properties = types.SimpleNamespace()
        self.properties = properties

    def __repr__(self) -> str:
        """
        >>> Contract.clear_cache()
        >>> ContractGroup.clear_cache()
        >>> contract = Contract.create('IBM', contract_group=ContractGroup.get('IBM'))
        >>> order = MarketOrder(contract=contract, timestamp=np.datetime64('2019-01-01T14:59'), qty=100)
        >>> print(Trade(contract, order, np.datetime64('2019-01-01 15:00'), 100, 10.2130000, 0.01))
        IBM 2019-01-01 15:00:00 qty: 100 prc: 10.213 fee: 0.01 order: IBM 2019-01-01 14:59:00 qty: 100 OrderStatus.OPEN
        """
        timestamp = _python_datetime(self.timestamp)
        fee = f"fee: {self.fee:.6g}" if self.fee else ""
        commission = f"commission: {self.commission:.6g}" if self.commission else ""
        return " ".join(
            part
            for part in (
                self.contract.symbol,
                _format(self.contract.properties),
                f"{timestamp:%Y-%m-%d %H:%M:%S}",
                f"qty: {self.qty}",
                f"prc: {self.price:.6g}",
                fee,
                commission,
                f"order: {str(self.order).strip()}",
                _format(self.properties),
            )
            if part
        )


@dataclass
class RoundTripTrade:
    contract: Contract
    entry_order: Order
    exit_order: Order | None
    entry_timestamp: np.datetime64
    exit_timestamp: np.datetime64
    qty: int
    entry_price: float
    exit_price: float
    entry_reason: str | None
    exit_reason: str | None
    entry_commission: float
    exit_commission: float
    entry_properties: SimpleNamespace = field(default_factory=SimpleNamespace)
    exit_properties: SimpleNamespace = field(default_factory=SimpleNamespace)
    net_pnl: float = np.nan


if __name__ == "__main__":
    import doctest

    doctest.testmod(optionflags=doctest.NORMALIZE_WHITESPACE)
# $$_end_code
