# $$_ Lines starting with # $$_* autogenerated by jup_mini. Do not modify these
# $$_markdown
# # Strategy Components
# ## Purpose
# Helper components to build strategies with common use cases like VWAP entry and exit, and finite risk
# $$_end_markdown
# $$_code
# $$_ %%checkall
import math
from dataclasses import dataclass
from types import SimpleNamespace
from typing import Callable, Sequence, cast

import numpy as np

from gambit.account import Account
from gambit.boundaries import validate_price_value
from gambit.execution_costs import ChargeModel, FixedPercentageSlippage, PerUnitCharge, SlippageModel
from gambit.pq_types import Contract, ContractGroup, LimitOrder, MarketOrder, Order, TimeInForce, Trade, VWAPOrder
from gambit.pq_utils import assert_, get_child_logger
from gambit.strategy_contracts import PriceFunctionType, StrategyContextType
from gambit.strategy_inputs import PriceFuncArrayDict as PriceFuncArrayDict
from gambit.strategy_inputs import PriceFuncArrays as PriceFuncArrays
from gambit.strategy_inputs import PriceFuncDict as PriceFuncDict
from gambit.strategy_inputs import VectorIndicator as VectorIndicator
from gambit.strategy_inputs import VectorSignal as VectorSignal
from gambit.strategy_inputs import _timestamp_at as _timestamp_at
from gambit.strategy_inputs import get_contract_price_from_array_dict as get_contract_price_from_array_dict
from gambit.strategy_inputs import get_contract_price_from_dict as get_contract_price_from_dict

_logger = get_child_logger(__name__)




@dataclass
class SimpleMarketSimulator:
    """
    A function object with a signature of MarketSimulatorType.
    It can take into account slippage and commission
    >>> ContractGroup.clear_cache()
    >>> Contract.clear_cache()
    >>> put_symbol, call_symbol = 'SPX-P-3500-2023-01-19', 'SPX-C-4000-2023-01-19'
    >>> put_contract = Contract.create(put_symbol)
    >>> call_contract = Contract.create(call_symbol)
    >>> basket = Contract.create('test_contract')
    >>> basket.components = [(put_contract, -1), (call_contract, 1)]
    >>> timestamp = np.datetime64('2023-01-03 14:35')
    >>> price_func = PriceFuncDict({put_symbol: {timestamp: 4.8}, call_symbol: {timestamp: 3.5}})
    >>> order = MarketOrder(contract=basket, timestamp=timestamp, qty=10, reason_code='TEST')
    >>> sim = SimpleMarketSimulator(price_func=price_func, slippage_pct=0)
    >>> out = sim([order], 0, np.array([timestamp]), {}, {}, SimpleNamespace())
    >>> assert(len(out) == 1)
    >>> assert(math.isclose(out[0].price, -1.3))
    >>> assert(out[0].qty == 10)
    """

    price_func: PriceFunctionType
    slippage_pct: float
    commission: float
    price_rounding: int
    post_trade_func: Callable[[Trade, StrategyContextType], None] | None
    slippage_model: SlippageModel
    commission_model: ChargeModel
    fee_model: ChargeModel

    def __init__(
        self,
        price_func: PriceFunctionType,
        slippage_pct: float = 0.0,
        commission: float = 0,
        price_rounding: int = 3,
        post_trade_func: Callable[[Trade, StrategyContextType], None] | None = None,
        slippage_model: SlippageModel | None = None,
        commission_model: ChargeModel | None = None,
        fee_model: ChargeModel | None = None,
    ) -> None:
        """
        Args:
            price_func: A function that we use to get the price to execute at
            slippage_pct: Slippage per dollar transacted.
                Meant to simulate the difference between bid/ask mid and execution price
            commission: Fee paid to broker per unit traded
        """
        self.price_func = price_func
        self.slippage_pct = slippage_pct
        self.commission = commission
        self.price_rounding = price_rounding
        self.post_trade_func = post_trade_func
        self.slippage_model = slippage_model or FixedPercentageSlippage(slippage_pct)
        self.commission_model = commission_model or PerUnitCharge(commission)
        self.fee_model = fee_model or PerUnitCharge()

    def __call__(
        self,
        orders: Sequence[Order],
        i: int,
        timestamps: np.ndarray,
        indicators: dict[str, SimpleNamespace],
        signals: dict[str, SimpleNamespace],
        strategy_context: SimpleNamespace,
    ) -> list[Trade]:
        """TODO: code for stop orders"""
        trades = []
        timestamp = _timestamp_at(timestamps, i)
        for order in orders:
            if not isinstance(order, MarketOrder) and not isinstance(order, LimitOrder):
                continue
            contract = order.contract
            if not contract.is_basket():
                raw_price = validate_price_value(
                    self.price_func(contract, timestamps, i, strategy_context),
                    symbol=contract.symbol,
                    timestamp=timestamp,
                    source="market simulator price callback",
                )
            else:
                raw_price = 0.0
                for _contract, ratio in contract.components:
                    component_price = validate_price_value(
                        self.price_func(_contract, timestamps, i, strategy_context),
                        symbol=_contract.symbol,
                        timestamp=timestamp,
                        source="market simulator basket price callback",
                    )
                    raw_price += component_price * ratio
                    if np.isnan(raw_price):
                        break
            if np.isnan(raw_price):
                continue
            slippage = self.slippage_model.adjustment(order, raw_price)
            price = validate_price_value(
                raw_price + slippage,
                symbol=contract.symbol,
                timestamp=timestamp,
                source="slippage model",
                allow_missing=False,
            )
            price = round(price, self.price_rounding)
            if isinstance(order, LimitOrder) and np.isfinite(order.limit_price):
                is_marketable = (order.qty > 0 and price <= order.limit_price) or (
                    order.qty < 0 and price >= order.limit_price
                )
                if not is_marketable:
                    continue
            commission = self.commission_model.charge(order, price)
            fee = self.fee_model.charge(order, price)
            trade = Trade(
                contract=order.contract,
                order=order,
                timestamp=timestamp,
                qty=order.qty,
                price=price,
                fee=fee,
                commission=commission,
            )
            order.fill()
            trades.append(trade)
            if self.post_trade_func is not None:
                self.post_trade_func(trade, strategy_context)
        return trades


@dataclass
class PercentOfEquityTradingRule:
    """
    A rule that trades a percentage of equity.

    Args:
        reason_code: Reason for entering the order, used for display
        equity_percent: Percentage of equity used to size order
        long: Whether We want to go long or short
        allocate_risk: If set, we divide the max risk by number of trades. Otherwise each trade will be alloated max risk
        limit_increment: If not nan, we add or subtract this number from current market price (if selling or buying respectively)
            and create a limit order. If nan, we create market orders
        price_func: The function we use to get intraday prices
    """

    reason_code: str
    price_func: PriceFunctionType
    equity_percent: float = 0.1  # use 10% of equity by default
    long: bool = True
    allocate_risk: bool = False
    limit_increment: float = math.nan

    def __call__(
        self,
        contract_group: ContractGroup,
        i: int,
        timestamps: np.ndarray,
        indicator_values: SimpleNamespace,
        signal_values: np.ndarray,
        account: Account,
        current_orders: Sequence[Order],
        strategy_context: StrategyContextType,
    ) -> list[Order]:

        timestamp = _timestamp_at(timestamps, i)

        contracts = contract_group.get_contracts()
        orders: list[Order] = []
        for contract in contracts:
            entry_price_est = self.price_func(contract, timestamps, i, strategy_context)
            if math.isnan(entry_price_est):
                return []

            curr_equity = account.equity(timestamp)
            risk_amount = self.equity_percent * curr_equity
            order_qty = risk_amount / entry_price_est
            if self.allocate_risk:
                order_qty /= len(contracts)  # divide up qty equally between all contracts
            if not self.long:
                order_qty *= -1
            order_qty = math.floor(order_qty) if order_qty > 0 else math.ceil(order_qty)
            if math.isclose(order_qty, 0.0):
                return []

            if math.isfinite(self.limit_increment):
                entry_price_est = self.price_func(contract, timestamps, i, strategy_context)
                entry_price_est -= np.sign(order_qty) * self.limit_increment

                limit_order = LimitOrder(
                    contract=contract,
                    timestamp=timestamp,
                    qty=order_qty,
                    limit_price=entry_price_est,
                    reason_code=self.reason_code,
                )
                orders.append(limit_order)
            else:
                market_order = MarketOrder(
                    contract=contract, timestamp=timestamp, qty=order_qty, reason_code=self.reason_code
                )
                orders.append(market_order)
        return orders


@dataclass
class VWAPEntryRule:
    """
    A rule that generates VWAP orders

    Args:
        reason_code: Reason for each order. For display purposes
        vwap_minutes: How long the vwap period is. For example, a 5 minute vwap order will execute at 5 minute vwap
        from when it is sent to the market
        price_func: A function that this rule uses to get market price at a given timestamp
        long: Whether we want to go long or short
        percent_of_equity: Order qty is calculated so that if the stop price is reached, we lose this amount
        stop_price_ind: Don't enter if estimated entry price is
            market price <= stop price + min_price_diff_pct * market_price (for long orders) or the opposite for short orders
        min_price_diff_pct: See stop_price_ind
    """

    reason_code: str
    vwap_minutes: int
    price_func: PriceFunctionType
    long: bool
    percent_of_equity: float
    stop_price_ind: str | None
    min_price_diff_pct: float
    single_entry_per_day: bool

    def __init__(
        self,
        reason_code: str,
        vwap_minutes: int,
        price_func: PriceFunctionType,
        long: bool = True,
        percent_of_equity: float = 0.1,
        stop_price_ind: str | None = None,
        min_price_diff_pct: float = 0,
        single_entry_per_day: bool = False,
    ) -> None:
        self.reason_code = reason_code
        self.price_func = price_func
        self.long = long
        self.vwap_minutes = vwap_minutes
        self.percent_of_equity = percent_of_equity
        self.stop_price_ind = stop_price_ind
        self.min_price_diff_pct = min_price_diff_pct
        self.single_entry_per_day = single_entry_per_day

    def __call__(
        self,
        contract_group: ContractGroup,
        i: int,
        timestamps: np.ndarray,
        indicator_values: SimpleNamespace,
        signal_values: np.ndarray,
        account: Account,
        current_orders: Sequence[Order],
        strategy_context: StrategyContextType,
    ) -> list[Order]:
        timestamp = _timestamp_at(timestamps, i)
        if self.single_entry_per_day:
            date = cast(np.datetime64, timestamp.astype("M8[D]"))
            if any(account.get_trades_for_date(contract.symbol, date) for contract in contract_group.get_contracts()):
                return []

        for order in current_orders:
            if order.contract.contract_group == contract_group and order.is_open():
                return []

        orders: list[Order] = []
        contracts = contract_group.get_contracts()
        for contract in contracts:
            entry_price_est = self.price_func(contract, timestamps, i, strategy_context)
            if math.isnan(entry_price_est):
                return []

            if self.stop_price_ind:
                _stop_price_ind = getattr(indicator_values, self.stop_price_ind)
                stop_price = _stop_price_ind[i]
                if self.long and (entry_price_est - stop_price) < self.min_price_diff_pct * entry_price_est:
                    return []
                if not self.long and (stop_price - entry_price_est) < self.min_price_diff_pct * entry_price_est:
                    return []
            else:
                stop_price = math.nan

            curr_equity = account.equity(timestamp)
            risk_amount = self.percent_of_equity * curr_equity
            order_qty = risk_amount / (entry_price_est - stop_price)
            order_qty /= len(contracts)  # divide up equity percentage equally
            order_qty = math.floor(order_qty) if order_qty > 0 else math.ceil(order_qty)
            if math.isclose(order_qty, 0.0):
                return []
            vwap_end_time = timestamp + np.timedelta64(self.vwap_minutes, "m")
            order = VWAPOrder(
                contract=contract,
                timestamp=timestamp,
                vwap_stop=stop_price,
                vwap_end_time=vwap_end_time,
                qty=order_qty,
                time_in_force=TimeInForce.GTC,
                reason_code=self.reason_code,
            )
            orders.append(order)
        return [order]


@dataclass
class VWAPCloseRule:
    """
    Rule to close out a position at vwap price
    Args:
        reason_code: Reason_code: Reason for each order. For display purposes
        vwap_minutes: How long the vwap period is. For example, a 5 minute vwap order will execute at 5 minute vwap
    """

    reason_code: str
    vwap_minutes: int

    def __init__(self, vwap_minutes: int, reason_code: str) -> None:
        self.vwap_minutes = vwap_minutes
        self.reason_code = reason_code

    def __call__(
        self,
        contract_group: ContractGroup,
        i: int,
        timestamps: np.ndarray,
        indicator_values: SimpleNamespace,
        signal_values: np.ndarray,
        account: Account,
        current_orders: Sequence[Order],
        strategy_context: StrategyContextType,
    ) -> list[Order]:
        timestamp = _timestamp_at(timestamps, i)
        for order in current_orders:
            if order.contract.contract_group == contract_group and order.is_open():
                return []
        positions = account.positions(contract_group, timestamp)
        orders: list[Order] = []
        for contract, qty in positions:
            # assert len(positions) == 1, f'expected 1 positions, got: {positions}'
            vwap_end_time = timestamp + np.timedelta64(self.vwap_minutes, "m")
            order = VWAPOrder(
                contract=contract,
                timestamp=timestamp,
                vwap_end_time=vwap_end_time,
                qty=-qty,
                time_in_force=TimeInForce.GTC,
                reason_code=self.reason_code,
            )
            orders.append(order)
        return orders


@dataclass
class VWAPMarketSimulator:
    """
    A market simulator that simulates buying and selling at VWAP prices.
    This works with VWAP orders and ignores all other order types
    The order executes either:
    a. After the vwap end time defined in the VWAP order
    b. If marker price <= vwap stop price defined in the VWAP order for buy orders
    c. If market price >= vwap stop price for sell orders
    """

    price_indicator: str
    volume_indicator: str
    backup_price_indicator: str | None

    def __init__(self, price_indicator: str, volume_indicator: str, backup_price_indicator: str | None = None) -> None:
        """
        Args:
            price_indicator: An indicator that contains historical trade price per timestamp
            volume_indicator: An indicator that contains volume per timestamp
            backup_price_indicator: Execution price to use if price or volume is missing
        """
        self.price_indicator = price_indicator
        self.volume_indicator = volume_indicator
        self.backup_price_indicator = backup_price_indicator

    def __call__(
        self,
        orders: Sequence[Order],
        i: int,
        timestamps: np.ndarray,
        indicators: dict[str, SimpleNamespace],
        signals: dict[str, SimpleNamespace],
        strategy_context: SimpleNamespace,
    ) -> list[Trade]:
        trades = []
        timestamp = _timestamp_at(timestamps, i)
        for order in orders:
            if not isinstance(order, VWAPOrder):
                continue
            cg = order.contract.contract_group
            inds = indicators.get(cg.name)
            assert_(inds is not None, f"indicators not found for contract group: {cg} {timestamp} {i}")
            price_ind = getattr(inds, self.price_indicator)
            assert_(
                price_ind is not None,
                f"indicator: {self.price_indicator} not found for contract group: {cg} {timestamp} {i}",
            )
            volume_ind = getattr(inds, self.volume_indicator)
            assert_(
                volume_ind is not None,
                f"indicator: {self.volume_indicator} not found for contract group: {cg} {timestamp} {i}",
            )
            end_order = False
            if math.isfinite(order.vwap_stop) and (
                (order.qty >= 0 and price_ind[i] <= order.vwap_stop)
                or (order.qty < 0 and price_ind[i] >= order.vwap_stop)
            ):
                end_order = True
            if (
                not end_order
                and timestamp < order.vwap_end_time
                and i != len(timestamps) - 1
                and not timestamps[i + 1].astype("M8[D]") > timestamps[i].astype("M8[D]")
            ):
                continue
            mask = (price_ind > 0) & (volume_ind > 0)
            if end_order:
                mask &= (timestamps >= order.timestamp) & (timestamps <= timestamp)
            else:
                mask &= (timestamps >= order.timestamp) & (timestamps <= order.vwap_end_time)
            amt = price_ind[mask] * volume_ind[mask]
            if not len(amt):
                _logger.info(f"using backup price for {cg} {timestamp} {i} qty: {order.qty} {order}")
                assert_(
                    self.backup_price_indicator is not None,
                    f"backup price indicator not found and no vwap found for: {cg} {timestamp} {i}",
                )
                _backup_price_ind = getattr(inds, cast(str, self.backup_price_indicator))
                assert_(_backup_price_ind is not None, f"backup price indicator not found for: {cg} {timestamp} {i}")
                vwap = _backup_price_ind[i]
            else:
                vwap = np.sum(amt) / np.sum(volume_ind[mask])
            assert_(vwap >= 0)
            fill_qty = order.qty
            if end_order:
                timestamp_ns = int(timestamp.astype("datetime64[ns]").astype(np.int64))
                order_timestamp_ns = int(order.timestamp.astype("datetime64[ns]").astype(np.int64))
                vwap_end_ns = int(order.vwap_end_time.astype("datetime64[ns]").astype(np.int64))
                fill_fraction = (timestamp_ns - order_timestamp_ns) / (vwap_end_ns - order_timestamp_ns)
                fill_fraction = min(fill_fraction, 1)
                fill_qty = float(np.fix(order.qty * fill_fraction))
                if math.isclose(fill_qty, 0.0):
                    order.cancel()
                    continue
            order.fill(fill_qty)
            order.cancel()
            trade = Trade(order.contract, order, timestamp, fill_qty, vwap)
            trades.append(trade)
        return trades


ContractFilterType = Callable[
    [ContractGroup, int, np.ndarray, SimpleNamespace, np.ndarray, Account, Sequence[Order], StrategyContextType],
    list[str],
]


@dataclass
class BracketOrderEntryRule:
    """
    A rule that generates orders with stops

    Args:
        reason_code: Reason for the orders created used for display
        price_func: A function that returns price given a contract and timestamp
        long: whether we want to go long or short
        percent_of_equity: How much to risk per trade as a percentage of current equity.
            Used to calculate order qty so that if we get stopped out, we don't lose
            more than this amount. Of course if price gaps up or down rather than moving smoothly,
            we may lose more.
        stop_return_func: A function that gives us the distance between entry price and stop price
        min_stop_return: We will not enter if the stop_return is closer than this percent to the stop.
            Otherwise, we get very large trade sizes
        max_position_size: An order should not result in a position that is greater than this percent
            of the portfolio
        contract_filter: A function that takes similar arguments as a rule (with ContractGroup) replaced by
            Contract but returns a list of contract names for each positive signal timestamp. For example,
            for a strategy that trades 5000 stocks, you may want to construct a single signal and apply it
            to different contracts at different times, rather than create 5000 signals that will call your rule
            5000 times every time the signal is true.

    >>> timestamps = np.arange(np.datetime64('2023-01-01'), np.datetime64('2023-01-05'))
    >>> sig_values = np.full(len(timestamps), False)
    >>> aapl_prices = np.array([100.1, 100.2, 100.3, 100.4])
    >>> ibm_prices = np.array([200.1, 200.2, 200.3, 200.4])
    >>> aapl_stops = np.array([-0.5, -0.3, -0.2, -0.01])
    >>> ibm_stops=  np.array([-0.5, -0.3, -0.2, -0.15])
    >>> price_dict = {'AAPL': (timestamps, aapl_prices), 'IBM': (timestamps, ibm_prices)}
    >>> stop_dict = {'AAPL': (timestamps, aapl_stops), 'IBM': (timestamps, ibm_stops)}
    >>> price_func = PriceFuncArrayDict(price_dict)
    >>> fr = BracketOrderEntryRule('TEST_ENTRY', price_func, long=False)
    >>> default_cg = ContractGroup.get('DEFAULT')
    >>> default_cg.clear_cache()
    >>> default_cg.add_contract(Contract.get_or_create('AAPL'))
    >>> default_cg.add_contract(Contract.get_or_create('IBM'))
    >>> account = SimpleNamespace()
    >>> account.equity = lambda x: 1e6
    >>> orders = fr(default_cg, 1, timestamps, SimpleNamespace(), sig_values, account, [], SimpleNamespace())
    >>> assert len(orders) == 2 and orders[0].qty == -998 and orders[1].qty == -499
    >>> stop_return_func = PriceFuncArrayDict(stop_dict)
    >>> fr = BracketOrderEntryRule('TEST_ENTRY', price_func, long=True, stop_return_func=stop_return_func, min_stop_return=-0.1)
    >>> orders = fr(default_cg, 2, timestamps, SimpleNamespace(), sig_values, account, [], SimpleNamespace())
    >>> assert len(orders) == 2 and orders[0].qty == 4985 and orders[1].qty == 2496
    >>> orders = fr(default_cg, 3, timestamps, SimpleNamespace(), sig_values, account, [], SimpleNamespace())
    >>> assert len(orders) == 1 and orders[0].qty == 3326
    """

    reason_code: str
    price_func: PriceFunctionType
    long: bool
    percent_of_equity: float
    min_stop_returnt: float
    max_position_size: float
    single_entry_per_day: bool
    contract_filter: ContractFilterType | None
    stop_return_func: PriceFunctionType | None

    def __init__(
        self,
        reason_code: str,
        price_func: PriceFunctionType,
        long: bool = True,
        percent_of_equity: float = 0.1,
        min_stop_return: float = 0,
        max_position_size: float = 0,
        single_entry_per_day: bool = False,
        contract_filter: ContractFilterType | None = None,
        stop_return_func: PriceFunctionType | None = None,
    ) -> None:
        self.reason_code = reason_code
        self.price_func = price_func
        self.long = long
        self.percent_of_equity = percent_of_equity
        self.stop_return_func = stop_return_func
        self.min_stop_return = min_stop_return
        self.max_position_size = max_position_size
        self.single_entry_per_day = single_entry_per_day
        self.contract_filter = contract_filter

    def __call__(
        self,
        contract_group: ContractGroup,
        i: int,
        timestamps: np.ndarray,
        indicator_values: SimpleNamespace,
        signal_values: np.ndarray,
        account: Account,
        current_orders: Sequence[Order],
        strategy_context: StrategyContextType,
    ) -> list[Order]:
        timestamp = _timestamp_at(timestamps, i)
        date = cast(np.datetime64, timestamp.astype("M8[D]"))

        contracts: list[Contract] = []
        if self.contract_filter is not None:
            names = self.contract_filter(
                contract_group,
                i,
                timestamps,
                indicator_values,
                signal_values,
                account,
                current_orders,
                strategy_context,
            )
            for name in names:
                _contract = Contract.get(name)
                if _contract is None:
                    continue
                contracts.append(_contract)
        else:
            contracts = contract_group.get_contracts()

        orders: list[Order] = []
        for contract in contracts:
            if self.single_entry_per_day:
                trades = account.get_trades_for_date(contract.symbol, date)
                if len(trades):
                    continue

            entry_price_est = self.price_func(contract, timestamps, i, strategy_context)
            if math.isnan(entry_price_est):
                continue

            stop_price = 0.0
            if self.stop_return_func is not None:
                stop_return = self.stop_return_func(contract, timestamps, i, strategy_context)
                assert_(stop_return < 0, f"stop_return must be negative: {stop_return} {timestamp} {contract.symbol}")
                if stop_return > self.min_stop_return:
                    _logger.info(
                        f"entry price estimate: {entry_price_est} too close to stop price: {stop_price}"
                        f" min stop return: {self.min_stop_return}"
                    )
                    continue
                if not self.long:
                    stop_return = -stop_return
                stop_price = entry_price_est * (1 + stop_return)
                if (self.long and entry_price_est <= stop_price) or (not self.long and entry_price_est >= stop_price):
                    _logger.info(f"entry price estimate: {entry_price_est} exceeds stop price: {stop_price}")
                    continue

            curr_equity = account.equity(timestamp)
            risk_amount = self.percent_of_equity * curr_equity
            order_qty = risk_amount / abs(entry_price_est - stop_price)

            if self.max_position_size > 0:
                max_qty = abs(self.max_position_size * curr_equity / entry_price_est)
                orig_qty = order_qty
                if max_qty < abs(orig_qty):
                    order_qty = max_qty * np.sign(orig_qty)
                    _logger.info(
                        f"max postion size exceeded: {contract} timestamp: {timestamp} max_qty: {max_qty}"
                        f" orig_qty: {orig_qty} new qty: {order_qty} max_qty: {max_qty} pos size: {self.max_position_size}"
                        f" curr_equity: {curr_equity} entry_price_est: {entry_price_est}"
                    )

            order_qty = math.floor(order_qty)
            if not self.long:
                order_qty = -order_qty
            if math.isclose(order_qty, 0.0):
                continue
            order = MarketOrder(
                contract=contract,
                timestamp=timestamp,
                qty=order_qty,
                reason_code=self.reason_code,
            )
            orders.append(order)
        return orders


@dataclass
class ClosePositionExitRule:
    """
    A rule to close out an open position

    Args:
        reason_code: the reason for closing out used for display purposes
        price_func: the function this rule uses to get market prices
        limit_increment: if not nan, we add or subtract this number from current market price (if selling or buying respectively)
            and create a limit order
    """

    reason_code: str
    price_func: PriceFunctionType
    limit_increment: float

    def __init__(self, reason_code: str, price_func: PriceFunctionType, limit_increment: float = math.nan) -> None:
        self.reason_code = reason_code
        self.price_func = price_func
        assert_(
            math.isnan(limit_increment) or limit_increment >= 0,
            f"limit_increment: {limit_increment} cannot be negative",
        )
        self.limit_increment = limit_increment

    def __call__(
        self,
        contract_group: ContractGroup,
        i: int,
        timestamps: np.ndarray,
        indicator_values: SimpleNamespace,
        signal_values: np.ndarray,
        account: Account,
        current_orders: Sequence[Order],
        strategy_context: StrategyContextType,
    ) -> list[Order]:
        timestamp = _timestamp_at(timestamps, i)
        positions = account.positions(contract_group, timestamp)
        orders: list[Order] = []
        for contract, qty in positions:
            if math.isfinite(self.limit_increment):
                exit_price_est = self.price_func(contract, timestamps, i, strategy_context)
                if qty >= 0:
                    exit_price_est += self.limit_increment
                else:
                    exit_price_est -= self.limit_increment
                limit_order = LimitOrder(
                    contract=contract,
                    timestamp=timestamp,
                    qty=-qty,
                    limit_price=exit_price_est,
                    reason_code=self.reason_code,
                )
                orders.append(limit_order)
                continue
            order = MarketOrder(contract=contract, timestamp=timestamp, qty=-qty, reason_code=self.reason_code)
            orders.append(order)
        return orders


@dataclass
class StopReturnExitRule:
    """
    A rule that exits any given positions if a stop is hit.
    You should set entry_price in the strategy context in the market simulator when you enter a position
    """

    reason_code: str
    price_func: PriceFunctionType
    stop_return_func: PriceFunctionType

    def __call__(
        self,
        contract_group: ContractGroup,
        i: int,
        timestamps: np.ndarray,
        indicator_values: SimpleNamespace,
        signal_values: np.ndarray,
        account: Account,
        current_orders: Sequence[Order],
        context: StrategyContextType,
    ) -> list[Order]:

        timestamp = _timestamp_at(timestamps, i)
        date = cast(np.datetime64, timestamp.astype("M8[D]"))
        entry_prices: dict[str, float] = context.entry_prices[date]
        assert_(len(entry_prices) > 0, f"no symbols entered for: {date}")
        positions = account.positions(contract_group, timestamp)

        orders: list[Order] = []
        for contract, qty in positions:
            symbol = contract.symbol
            stop_ret = self.stop_return_func(contract, timestamps, i, context)
            assert_(stop_ret < 0, f"stop_return must be negative: {stop_ret} {timestamp} {symbol}")
            entry_price = entry_prices[symbol]
            if qty < 0:
                stop_ret = -stop_ret
            stop_price = entry_price * (1 + stop_ret)
            curr_price = self.price_func(contract, timestamps, i, context)
            if math.isnan(curr_price):
                continue
            if (qty > 0 and curr_price > stop_price) or (qty <= 0 and curr_price < stop_price):
                continue
            order = MarketOrder(contract=contract, timestamp=timestamp, qty=-qty, reason_code=self.reason_code)
            orders.append(order)
        return orders


if __name__ == "__main__":
    import doctest

    doctest.testmod(optionflags=doctest.NORMALIZE_WHITESPACE | doctest.ELLIPSIS)
# $$_end_code
