# $$_ Lines starting with # $$_* autogenerated by jup_mini. Do not modify these
# $$_code
# $$_ %%checkall
from __future__ import annotations

import math
import time
import types
from collections import defaultdict
from pprint import pformat
from types import SimpleNamespace
from typing import Any, Callable, Sequence, TypeAlias, Union, cast

import numpy as np
import polars as pl

from gambit.account import Account
from gambit.backtest_result import BacktestResult, BacktestTelemetry, StageTelemetry
from gambit.boundaries import BacktestCallbackError, validate_strategy_timestamps
from gambit.calculation import CalculationContext
from gambit.callback_contracts import validate_market_trades, validate_rule_orders, validate_stage_values
from gambit.configuration import RunConfiguration, RunProvenance
from gambit.execution_snapshots import snapshot_order
from gambit.market_data import MarketDataValidationReport
from gambit.pq_types import ContractGroup, Order, OrderStatus, RoundTripTrade, TimeInForce, Trade
from gambit.pq_utils import assert_, get_child_logger, series_to_array
from gambit.risk import DecisionStatus, OrderDecision, RiskContext, RiskPolicy, decide_order
from gambit.risk_measures import RiskMeasure, RiskResult, calculate_risk
from gambit.risk_reporting import PortfolioRiskReport, StressScenario, analyze_account_risk
from gambit.stages import ExecutionStage, IndicatorStage, RuleStage, SignalStage, StageGraph, StageNode
from gambit.strategy_contracts import PriceFunctionType, ReturnReporter, StrategyContextType
from gambit.strategy_validation import validate_dependency_scopes, validated_stage_groups, validated_stage_names

IndicatorType: TypeAlias = IndicatorStage
SignalType: TypeAlias = SignalStage
RuleType: TypeAlias = RuleStage
MarketSimulatorType: TypeAlias = ExecutionStage

DateRangeType = Union[tuple[str, str], tuple[np.datetime64, np.datetime64]]

# Placeholder for orders to create later
OrderTupType = tuple[RuleType, ContractGroup, dict[str, Any]]

PlotPropertiesType = dict[str, dict[str, Any]]

NAT = np.datetime64("NaT", "ns")

_logger = get_child_logger(__name__)


def _concat_artifact_frames(frames: dict[str, pl.DataFrame]) -> pl.DataFrame:
    if not frames:
        return pl.DataFrame(schema={"artifact": pl.String})
    return pl.concat(
        [
            frame.with_columns(pl.lit(name).alias("artifact")).select("artifact", *frame.columns)
            for name, frame in sorted(frames.items())
        ],
        how="diagonal_relaxed",
    )


def _concat_report_frames(reports: dict[str, PortfolioRiskReport], field: str) -> pl.DataFrame:
    if not reports:
        return pl.DataFrame(schema={"artifact": pl.String, "timestamp": pl.Datetime("ns")})
    frames = {
        name: getattr(report, field).with_columns(
            pl.lit(report.timestamp.astype("datetime64[ns]")).alias("timestamp")
        )
        for name, report in reports.items()
    }
    return _concat_artifact_frames(frames)


def _restore_order_states(states: Sequence[tuple[Order, float, OrderStatus]]) -> None:
    for order, qty, status in states:
        order.qty = qty
        order.status = status


class Strategy:
    def __init__(
        self,
        timestamps: np.ndarray,
        contract_groups: Sequence[ContractGroup],
        price_function: PriceFunctionType,
        starting_equity: float = 1.0e6,
        pnl_calc_time: int = 16 * 60 + 1,
        trade_lag: int = 0,
        run_final_calc: bool = True,
        log_trades: bool = True,
        log_orders: bool = False,
        strategy_context: StrategyContextType | None = None,
        return_reporter: ReturnReporter | None = None,
    ) -> None:
        """
        Args:
            timestamps (np.array of np.datetime64): The "heartbeat" of the strategy.  We will evaluate trading rules and
                simulate the market at these times.
            contract_groups: The contract groups we will potentially trade.
            price_function: A function that returns the price of a contract at a given timestamp
            starting_equity: Starting equity in Strategy currency.  Default 1.e6
            pnl_calc_time: Time of day used to calculate PNL. Default 16 * 60 + 1 (4:01 pm).
            trade_lag: Number of bars you want between the order and the trade.  For example, if you think it will take
                5 seconds to place your order in the market, and your bar size is 1 second, set this to 5.  Set this to 0 if you
                want to execute your trade at the same time as you place the order, for example, if you have daily bars.  Default 0.
            run_final_calc: If set, calculates unrealized pnl and net pnl as well as realized pnl when strategy is done.
                If you don't need unrealized pnl, turn this off for faster run time. Default True
            strategy_context: A storage class where you can store key / value pairs relevant to this strategy.
                For example, you may have a pre-computed table of correlations that you use in the indicator or trade rule functions.
                If not set, the __init__ function will create an empty member strategy_context object that you can access.
            log_trades: If set, we log orders as they are created
            log_orders: If set, we log trades as they are created
            return_reporter: Optional analytics/presentation adapter. The evaluator-backed default is loaded lazily.
        """
        self.name = "main"  # Set by portfolio when running multiple strategies
        self.run_configuration = RunConfiguration(
            starting_equity=starting_equity,
            pnl_calc_time=pnl_calc_time,
            trade_lag=trade_lag,
            run_final_calc=run_final_calc,
            log_trades=log_trades,
            log_orders=log_orders,
        )
        self.provenance = RunProvenance(self.run_configuration)
        validate_strategy_timestamps(timestamps)
        if strategy_context is None:
            strategy_context = types.SimpleNamespace()
        self.strategy_context = strategy_context
        self._return_reporter = return_reporter
        self.account = Account(
            contract_groups, timestamps, price_function, strategy_context, starting_equity, pnl_calc_time
        )
        self.timestamps = self.account.timestamps
        self.contract_groups = self.account.contract_groups
        assert_(trade_lag >= 0, f"trade_lag cannot be negative: {trade_lag}")
        self.trade_lag = trade_lag
        self.run_final_calc = run_final_calc
        self.log_trades = log_trades
        self.log_orders = log_orders
        self.indicators: dict[str, IndicatorType] = {}
        self._indicator_functions: dict[tuple[str, int], IndicatorType] = {}
        self.signals: dict[str, SignalType] = {}
        self._signal_functions: dict[tuple[str, int], SignalType] = {}
        self.signal_values: dict[str, SimpleNamespace] = defaultdict(types.SimpleNamespace)
        self.rule_names: list[str] = []
        self.rules: dict[str, RuleType] = {}
        self.position_filters: dict[str, str | None] = {}
        self.rule_signals: dict[str, tuple[str, Sequence[Any]]] = {}
        self.market_sims: list[MarketSimulatorType] = []
        # a list of all orders created used for display
        self._orders: list[Order] = []
        self._current_orders: list[Order] = []
        self.risk_policies: list[RiskPolicy] = []
        self.order_decisions: list[OrderDecision] = []
        self._recorded_risk_results: dict[str, pl.DataFrame] = {}
        self._recorded_risk_reports: dict[str, PortfolioRiskReport] = {}
        self._recorded_validation_reports: dict[str, MarketDataValidationReport] = {}
        self._risk_result_requests: dict[str, tuple[CalculationContext, tuple[RiskMeasure, ...]]] = {}
        self._risk_report_requests: dict[
            str, tuple[CalculationContext, tuple[StressScenario, ...] | None, tuple[str, ...]]
        ] = {}
        self.indicator_deps: dict[str, list[str]] = {}
        self.indicator_cgroups: dict[str, tuple[ContractGroup, ...]] = {}
        self.indicator_values: dict[str, SimpleNamespace] = defaultdict(types.SimpleNamespace)
        self.signal_indicator_deps: dict[str, list[str]] = {}
        self.signal_deps: dict[str, list[str]] = {}
        self.signal_cgroups: dict[str, tuple[ContractGroup, ...]] = {}
        self.trades_iter: list[list] = [
            [] for x in range(len(timestamps))
        ]  # For debugging, we don't really need this as a member variable

    def record_input_fingerprint(self, name: str, fingerprint: str) -> None:
        """Attach an immutable input identity to this strategy's provenance."""
        self.provenance = self.provenance.with_input(name, fingerprint)

    def record_polars_input(self, name: str, frame: pl.DataFrame) -> None:
        """Fingerprint and attach a Polars input without retaining its data."""
        self.provenance = self.provenance.with_polars_input(name, frame)

    def risk_report(
        self,
        timestamp: np.datetime64 | CalculationContext,
        scenarios: Sequence[StressScenario] | None = None,
        attribution_by: Sequence[str] = ("contract_group",),
    ) -> PortfolioRiskReport:
        """Return a read-only exposure and stress report for this strategy account."""
        return analyze_account_risk(self.account, timestamp, scenarios, attribution_by)

    def calculate_risk(
        self, timestamp: np.datetime64 | CalculationContext, measures: Sequence[RiskMeasure]
    ) -> RiskResult:
        """Calculate typed measures into a common long-form Polars result."""
        context = CalculationContext.coerce(timestamp)
        report = analyze_account_risk(self.account, context)
        return calculate_risk(report.exposures, measures, context)

    @staticmethod
    def _require_artifact_name(name: str) -> None:
        if not name or not name.strip():
            raise ValueError("artifact name must be non-empty")

    def record_risk_result(self, name: str, result: RiskResult) -> None:
        """Record an already-calculated typed risk result for the run snapshot."""
        self._require_artifact_name(name)
        if name in self._recorded_risk_results:
            raise ValueError(f"risk result already recorded: {name}")
        self._recorded_risk_results[name] = result.data.clone()

    def record_risk_report(self, name: str, report: PortfolioRiskReport) -> None:
        """Record an already-calculated exposure and stress report."""
        self._require_artifact_name(name)
        if name in self._recorded_risk_reports:
            raise ValueError(f"risk report already recorded: {name}")
        self._recorded_risk_reports[name] = PortfolioRiskReport(
            report.timestamp,
            report.exposures.clone(),
            report.attribution.clone(),
            report.scenario_results.clone(),
        )

    def record_market_data_validation(self, name: str, report: MarketDataValidationReport) -> None:
        """Record validation findings without retaining the validated market data."""
        self._require_artifact_name(name)
        if name in self._recorded_validation_reports:
            raise ValueError(f"validation report already recorded: {name}")
        self._recorded_validation_reports[name] = report

    def request_risk_result(
        self,
        name: str,
        timestamp: np.datetime64 | CalculationContext,
        measures: Sequence[RiskMeasure],
    ) -> None:
        """Request named typed risk measures after backtest execution completes."""
        self._require_artifact_name(name)
        if name in self._risk_result_requests or name in self._recorded_risk_results:
            raise ValueError(f"risk result already requested or recorded: {name}")
        if not measures:
            raise ValueError("at least one risk measure is required")
        self._risk_result_requests[name] = (CalculationContext.coerce(timestamp), tuple(measures))

    def request_risk_report(
        self,
        name: str,
        timestamp: np.datetime64 | CalculationContext,
        scenarios: Sequence[StressScenario] | None = None,
        attribution_by: Sequence[str] = ("contract_group",),
    ) -> None:
        """Request a named exposure/stress report after execution completes."""
        self._require_artifact_name(name)
        if name in self._risk_report_requests or name in self._recorded_risk_reports:
            raise ValueError(f"risk report already requested or recorded: {name}")
        if not attribution_by:
            raise ValueError("attribution dimensions cannot be empty")
        selected_scenarios = None if scenarios is None else tuple(scenarios)
        self._risk_report_requests[name] = (
            CalculationContext.coerce(timestamp),
            selected_scenarios,
            tuple(attribution_by),
        )

    def _run_requested_analytics(self) -> None:
        for name, (context, scenarios, attribution_by) in self._risk_report_requests.items():
            self._recorded_risk_reports.pop(name, None)
            self.record_risk_report(name, self.risk_report(context, scenarios, attribution_by))
        for name, (context, measures) in self._risk_result_requests.items():
            self._recorded_risk_results.pop(name, None)
            self.record_risk_result(name, self.calculate_risk(context, measures))

    def add_indicator(
        self,
        name: str,
        indicator: IndicatorType,
        contract_groups: Sequence[ContractGroup] | None = None,
        depends_on: Sequence[str] | None = None,
    ) -> None:
        """
        Args:
            name: Name of the indicator
            indicator:  A function that takes strategy timestamps and other indicators and returns a numpy array
              containing indicator values.  The return array must have the same length as the timestamps object.
            contract_groups: Contract groups that this indicator applies to.  If not set, it applies to all contract groups. Default None.
            depends_on: Names of other indicators that we need to compute this indicator. Default None.
        """
        if not callable(indicator):
            raise TypeError("indicator must be callable")
        validated_groups = validated_stage_groups(
            contract_groups, self.contract_groups, operation="indicator registration"
        )
        dependencies = [] if depends_on is None else list(depends_on)
        existing_groups = self.indicator_cgroups.get(name, ())
        if any(group in existing_groups for group in validated_groups):
            raise ValueError(f"indicator {name!r} is already registered for one or more contract groups")
        if name in self.indicator_deps and self.indicator_deps[name] != dependencies:
            raise ValueError(f"indicator {name!r} registrations must declare identical dependencies")
        self.indicators.setdefault(name, indicator)
        self.indicator_deps[name] = dependencies
        self.indicator_cgroups[name] = (*existing_groups, *validated_groups)
        for group in validated_groups:
            self._indicator_functions[(name, id(group))] = indicator

    def add_signal(
        self,
        name: str,
        signal_function: SignalType,
        contract_groups: Sequence[ContractGroup] | None = None,
        depends_on_indicators: Sequence[str] | None = None,
        depends_on_signals: Sequence[str] | None = None,
    ) -> None:
        """
        Args:
            name (str): Name of the signal
            signal_function (function):  A function that takes timestamps and a dictionary of indicator value arrays and
                returns a numpy array
                containing signal values.  The return array must have the same length as the input timestamps
            contract_groups (list of :obj:`ContractGroup`, optional): Contract groups that this signal applies to.
                If not set, it applies to all contract groups.  Default None.
            depends_on_indicators (list of str, optional): Names of indicators that we need to compute this signal. Default None.
            depends_on_signals (list of str, optional): Names of other signals that we need to compute this signal. Default None.
        """
        if not callable(signal_function):
            raise TypeError("signal must be callable")
        validated_groups = validated_stage_groups(contract_groups, self.contract_groups, operation="signal registration")
        indicator_dependencies = [] if depends_on_indicators is None else list(depends_on_indicators)
        signal_dependencies = [] if depends_on_signals is None else list(depends_on_signals)
        existing_groups = self.signal_cgroups.get(name, ())
        if any(group in existing_groups for group in validated_groups):
            raise ValueError(f"signal {name!r} is already registered for one or more contract groups")
        if name in self.signal_indicator_deps and self.signal_indicator_deps[name] != indicator_dependencies:
            raise ValueError(f"signal {name!r} registrations must declare identical indicator dependencies")
        if name in self.signal_deps and self.signal_deps[name] != signal_dependencies:
            raise ValueError(f"signal {name!r} registrations must declare identical signal dependencies")
        self.signals.setdefault(name, signal_function)
        self.signal_indicator_deps[name] = indicator_dependencies
        self.signal_deps[name] = signal_dependencies
        self.signal_cgroups[name] = (*existing_groups, *validated_groups)
        for group in validated_groups:
            self._signal_functions[(name, id(group))] = signal_function

    def add_rule(
        self,
        name: str,
        rule_function: RuleType,
        signal_name: str,
        sig_true_values: Sequence[Any] | None = None,
        position_filter: str | None = None,
    ) -> None:
        """Add a trading rule.  Trading rules are guaranteed to run in the order in which you add them.  For example, if you set trade_lag to 0,
               and want to exit positions and re-enter new ones in the same bar, make sure you add the exit rule before you add the entry rule to the
               strategy.

        Args:
            name: Name of the trading rule
            rule_function: A trading rule function that returns a list of Orders
            signal_name: The strategy will call the trading rule function when the signal with this name matches sig_true_values
            sig_true_values: If the signal value at a bar is equal to one of these values,
                the Strategy will call the trading rule function.  Default [TRUE]
            position_filter: Can be "zero", "nonzero", "positive", "negative" or None.
                Rules are only triggered when the corresponding contract positions fit the criteria.
                For example, a positive rule is only triggered when the current position for that contract is > 0
                If not set, we don't look at the position before triggering the rule. Default None
        """

        if not isinstance(name, str) or not name:
            raise ValueError("rule name must be a non-empty string")
        if name in self.rule_names:
            raise ValueError(f"rule {name!r} is already registered")
        if not callable(rule_function):
            raise TypeError("rule must be callable")
        if not isinstance(signal_name, str) or not signal_name:
            raise ValueError("rule signal_name must be a non-empty string")
        if position_filter not in (None, "", "zero", "nonzero", "positive", "negative"):
            raise ValueError(f"invalid rule position_filter: {position_filter!r}")
        trigger_values = (True,) if sig_true_values is None else tuple(sig_true_values)
        normalized_position_filter = None if position_filter == "" else position_filter

        # Rules should be run in order
        self.rule_names.append(name)
        self.rule_signals[name] = (signal_name, trigger_values)
        self.rules[name] = rule_function
        self.position_filters[name] = normalized_position_filter

    def add_market_sim(self, market_sim_function: MarketSimulatorType) -> None:
        """Add a market simulator.  A market simulator is a function that takes orders as input and returns trades."""
        if not callable(market_sim_function):
            raise TypeError("market simulator must be callable")
        self.market_sims.append(market_sim_function)

    def add_risk_policy(self, risk_policy: RiskPolicy) -> None:
        """Add a pre-trade policy, evaluated in registration order."""
        policy_name = getattr(risk_policy, "name", None)
        if not isinstance(policy_name, str) or not policy_name:
            raise TypeError("risk policy must expose a non-empty string name")
        if not callable(getattr(risk_policy, "evaluate", None)):
            raise TypeError("risk policy must expose a callable evaluate method")
        self.risk_policies.append(risk_policy)

    def stage_graph(self) -> StageGraph:
        """Return the declared computation pipeline as a dependency graph."""
        nodes: list[StageNode] = []
        for name in self.indicators:
            nodes.append(
                StageNode(
                    f"indicator:{name}",
                    "indicator",
                    tuple(f"indicator:{dependency}" for dependency in self.indicator_deps[name]),
                )
            )
        for name in self.signals:
            dependencies = [f"indicator:{dependency}" for dependency in self.signal_indicator_deps[name]]
            dependencies.extend(f"signal:{dependency}" for dependency in self.signal_deps[name])
            nodes.append(StageNode(f"signal:{name}", "signal", tuple(dependencies)))
        for name in self.rule_names:
            signal_name = self.rule_signals[name][0]
            nodes.append(StageNode(f"rule:{name}", "rule", (f"signal:{signal_name}",)))
        rule_dependencies = tuple(f"rule:{name}" for name in self.rule_names)
        for index, _market_simulator in enumerate(self.market_sims):
            nodes.append(StageNode(f"execution:{index}", "execution", rule_dependencies))
        accounting_dependencies = tuple(f"execution:{index}" for index in range(len(self.market_sims)))
        if not accounting_dependencies:
            accounting_dependencies = rule_dependencies
        nodes.append(StageNode("accounting:main", "accounting", accounting_dependencies))
        return StageGraph(nodes)

    def validate_stage_graph(self) -> tuple[str, ...]:
        """Validate dependencies and return deterministic execution order metadata."""
        order = self.stage_graph().topological_order()
        validate_dependency_scopes(
            self.indicator_cgroups,
            self.indicator_deps,
            self.signal_cgroups,
            self.signal_indicator_deps,
            self.signal_deps,
        )
        return order

    def run_indicators(
        self,
        indicator_names: Sequence[str] | None = None,
        contract_groups: Sequence[ContractGroup] | None = None,
        clear_all: bool = False,
    ) -> None:
        """Calculate values of the indicators specified and store them.

        Args:
            indicator_names: list of indicator names.  If None (default) run all indicators
            contract_groups: Contract group to run this indicator for.  If None (default), we run it for all contract groups.
            clear_all: If set, clears all indicator values before running.  Default False.
        """
        indicator_names = validated_stage_names(
            indicator_names,
            tuple(self.indicators),
            operation="indicator",
        )
        contract_groups = validated_stage_groups(
            contract_groups, self.contract_groups, operation="indicator execution"
        )

        if clear_all:
            self.indicator_values = defaultdict(types.SimpleNamespace)

        indicator_names = tuple(
            name
            for name in indicator_names
            if any(
                requested_group is stage_group
                for requested_group in contract_groups
                for stage_group in self.indicator_cgroups[name]
            )
        )

        for cgroup in contract_groups:
            cgroup_ind_namespace = self.indicator_values[cgroup.name]
            for indicator_name in indicator_names:
                # First run all parents
                parent_names = self.indicator_deps[indicator_name]
                for parent_name in parent_names:
                    if cgroup.name in self.indicator_values and hasattr(cgroup_ind_namespace, parent_name):
                        continue
                    self.run_indicators([parent_name], [cgroup])

                # Now run the actual indicator
                if cgroup.name in self.indicator_values and hasattr(cgroup_ind_namespace, indicator_name):
                    continue
                indicator_function = self._indicator_functions[(indicator_name, id(cgroup))]

                parent_values = types.SimpleNamespace()

                for parent_name in parent_names:
                    setattr(parent_values, parent_name, getattr(cgroup_ind_namespace, parent_name))

                try:
                    indicator_values = series_to_array(
                        indicator_function(cgroup, self.timestamps, parent_values, self.strategy_context)
                    )
                    validated_values = validate_stage_values(
                        indicator_values,
                        len(self.timestamps),
                        stage=f"indicator {indicator_name!r}",
                    )
                except Exception as exc:
                    raise BacktestCallbackError(
                        f"indicator callback {indicator_name!r} failed for contract group {cgroup.name}"
                    ) from exc
                setattr(cgroup_ind_namespace, indicator_name, validated_values)

    def run_signals(
        self,
        signal_names: Sequence[str] | None = None,
        contract_groups: Sequence[ContractGroup] | None = None,
        clear_all: bool = False,
    ) -> None:
        """Calculate values of the signals specified and store them.

        Args:
            signal_names: list of signal names.  If None (default) run all signals
            contract_groups: Contract groups to run this signal for. If None (default), we run it for all contract groups.
            clear_all: If set, clears all signal values before running.  Default False.
        """
        signal_names = validated_stage_names(
            signal_names,
            tuple(self.signals),
            operation="signal",
        )
        contract_groups = validated_stage_groups(contract_groups, self.contract_groups, operation="signal execution")

        if clear_all:
            self.signal_values = defaultdict(types.SimpleNamespace)

        signal_names = tuple(
            name
            for name in signal_names
            if any(
                requested_group is stage_group
                for requested_group in contract_groups
                for stage_group in self.signal_cgroups[name]
            )
        )

        for cgroup in contract_groups:
            for signal_name in signal_names:
                if cgroup.name not in [cg.name for cg in self.signal_cgroups[signal_name]]:
                    continue
                # First run all parent signals
                parent_names = self.signal_deps[signal_name]
                for parent_name in parent_names:
                    if cgroup.name in self.signal_values and hasattr(self.signal_values[cgroup.name], parent_name):
                        continue
                    self.run_signals([parent_name], [cgroup])
                # Now run the actual signal
                if cgroup.name in self.signal_values and hasattr(self.signal_values[cgroup.name], signal_name):
                    continue
                signal_function = self._signal_functions[(signal_name, id(cgroup))]
                parent_values = types.SimpleNamespace()
                for parent_name in parent_names:
                    sig_vals = getattr(self.signal_values[cgroup.name], parent_name)
                    setattr(parent_values, parent_name, sig_vals)

                # Get indicators needed for this signal
                indicator_values = types.SimpleNamespace()
                for indicator_name in self.signal_indicator_deps[signal_name]:
                    setattr(
                        indicator_values, indicator_name, getattr(self.indicator_values[cgroup.name], indicator_name)
                    )

                try:
                    signal_output = series_to_array(
                        signal_function(
                            cgroup, self.timestamps, indicator_values, parent_values, self.strategy_context
                        )
                    )
                    validated_values = validate_stage_values(
                        signal_output,
                        len(self.timestamps),
                        stage=f"signal {signal_name!r}",
                    )
                except Exception as exc:
                    raise BacktestCallbackError(
                        f"signal callback {signal_name!r} failed for contract group {cgroup.name}"
                    ) from exc
                setattr(self.signal_values[cgroup.name], signal_name, validated_values)

    def _generate_order_iterations(
        self,
        rule_names: Sequence[str] | None = None,
        contract_groups: Sequence[ContractGroup] | None = None,
        start_date: np.datetime64 = NAT,
        end_date: np.datetime64 = NAT,
    ) -> None:
        """
        >>> class MockStrat:
        ...    def __init__(self):
        ...        self.timestamps = timestamps
        ...        self.trade_lag = 0
        ...        self.account = self
        ...        self.rules = {'rule_a': rule_a, 'rule_b': rule_b}
        ...        self.market_sims = {'ibm': market_sim_ibm, 'aapl': market_sim_aapl}
        ...        self.rule_signals = {'rule_a': ('sig_a', [1]), 'rule_b': ('sig_b', [1, -1])}
        ...        self.signal_values = {'IBM': types.SimpleNamespace(sig_a=np.array([0., 1., 1.]),
        ...                                                   sig_b = np.array([0., 0., 0.]) ),
        ...                               'AAPL': types.SimpleNamespace(sig_a=np.array([0., 0., 0.]),
        ...                                                    sig_b=np.array([0., -1., -1])
        ...                                                   )}
        ...        self.signal_cgroups = {'sig_a': [ibm, aapl], 'sig_b': [ibm, aapl]}
        ...        self.indicator_values = {'IBM': types.SimpleNamespace(), 'AAPL': types.SimpleNamespace()}
        >>>
        >>> def market_sim_aapl(): pass
        >>> def market_sim_ibm(): pass
        >>> def rule_a(): pass
        >>> def rule_b(): pass
        >>> timestamps = np.array(['2018-01-01', '2018-01-02', '2018-01-03'], dtype = 'M8[D]')
        >>> rule_names = ['rule_a', 'rule_b']
        >>> ContractGroup.clear_cache()
        >>> ibm = ContractGroup.get('IBM')
        >>> aapl = ContractGroup.get('AAPL')
        >>> contract_groups = [ibm, aapl]
        >>> start_date = np.datetime64('2018-01-01')
        >>> end_date = np.datetime64('2018-02-05')
        >>> strategy = MockStrat()
        >>> Strategy._generate_order_iterations(strategy, rule_names, contract_groups, start_date, end_date)
        >>> orders_iter = strategy.orders_iter
        >>> assert_(len(orders_iter[0]) == 0)
        >>> assert_(len(orders_iter[1]) == 2)
        >>> assert_(orders_iter[1][0][1] == ibm)
        >>> assert_(orders_iter[1][1][1] == aapl)
        >>> assert_(len(orders_iter[2]) == 2)
        """
        _start_date, _end_date = np.datetime64(start_date), np.datetime64(end_date)
        if rule_names is None:
            rule_names = self.rule_names
        if contract_groups is None:
            contract_groups = self.contract_groups

        num_timestamps = len(self.timestamps)

        # list of lists, i -> list of order tuple
        orders_iter: list[list[OrderTupType]] = [[] for x in range(num_timestamps)]

        for rule_name in rule_names:
            rule_function = self.rules[rule_name]
            for cgroup in contract_groups:
                signal_name, sig_true_values = self.rule_signals[rule_name]
                if cgroup.name not in [cg.name for cg in self.signal_cgroups[signal_name]]:
                    # We don't need to call this rule for this contract group
                    continue
                assert_(cgroup.name in self.signal_values, f"missing {cgroup.name} in signal_values")
                sig_values = getattr(self.signal_values[cgroup.name], signal_name).copy()
                timestamps = self.timestamps

                null_value = False if sig_values.dtype == np.dtype("bool") else np.nan

                if not np.isnat(_start_date):
                    start_idx = int(np.searchsorted(timestamps, _start_date))
                    sig_values[0:start_idx] = null_value

                if not np.isnat(_end_date):
                    end_idx = int(np.searchsorted(timestamps, _end_date))
                    sig_values[end_idx:] = null_value

                indices = np.nonzero(np.isin(sig_values[:num_timestamps], sig_true_values))[0]

                # Don't run rules on last index since we cannot fill any orders
                if len(indices) and indices[-1] == len(sig_values) - 1 and self.trade_lag > 0:
                    indices = indices[:-1]
                indicator_values = self.indicator_values[cgroup.name]
                iteration_params = {
                    "indicator_values": indicator_values,
                    "signal_values": sig_values,
                    "rule_name": rule_name,
                }
                for idx in indices:
                    orders_iter[idx].append((rule_function, cgroup, iteration_params))

        self.orders_iter = orders_iter

    def run_rules(
        self,
        rule_names: Sequence[str] | None = None,
        contract_groups: Sequence[ContractGroup] | None = None,
        start_date: np.datetime64 = NAT,
        end_date: np.datetime64 = NAT,
    ) -> None:
        """
        Run trading rules.

        Args:
            rule_names: list of rule names.  If None (default) run all rules
            contract_groups: Contract groups to run this rule for.  If None (default), we run it for all contract groups.
            start_date: Run rules starting from this date. Default None
            end_date: Don't run rules after this date.  Default None
        """
        validated_rule_names = validated_stage_names(rule_names, self.rule_names, operation="rule")
        validated_groups = validated_stage_groups(contract_groups, self.contract_groups, operation="rule execution")
        self._generate_order_iterations(validated_rule_names, validated_groups, start_date, end_date)

        # Now we know which rules, contract groups need to be applied for each iteration, go through each iteration and apply them
        # in the same order they were added to the strategy
        for i in range(len(self.orders_iter)):
            self._run_iteration(i)

        if self.run_final_calc:
            self.account.calc(cast(np.datetime64, self.timestamps[-1]))

    def _run_iteration(self, i: int) -> None:
        # first execute open orders so that positions get updated before running rules
        # If the lag is 0, then run rules one by one, and after each rule, run market sim to generate trades and update
        # positions. For example, if we have a rule to exit a position and enter a new one, we should make sure
        # positions are updated after the first rule before running the second rule.  If the lag is not 0,
        # run all rules and collect the orders, we don't need to run market sim after each rule
        self._sim_market(i)

        rules = self.orders_iter[i]

        for j, (rule_function, contract_group, params) in enumerate(rules):
            orders = self._get_orders(i, rule_function, contract_group, params)
            if self.log_orders and len(orders) > 0:
                if len(orders) > 1:
                    _logger.info("ORDERS:" + "".join([f"\n {order}" for order in orders]))
                else:
                    _logger.info(f"ORDER: {orders[0]}")

            accepted_orders: list[Order] = []
            for order in orders:
                context = RiskContext(
                    self.account,
                    cast(np.datetime64, self.timestamps[i]),
                    [*self._current_orders, *accepted_orders],
                )
                decision = decide_order(order, context, self.risk_policies)
                self.order_decisions.append(decision)
                if decision.status is DecisionStatus.ACCEPTED:
                    accepted_orders.append(order)
                else:
                    order.cancel()

            self._orders += orders
            self._current_orders += accepted_orders
            # _logger.info(f'current_orders: {self._current_orders}')

            if self.trade_lag == 0:
                # we don't need to do this for the last rule function
                # since the sim_market at the beginning of this function will take care of it
                # in the next iteration
                self._sim_market(i)
            else:
                self._update_current_orders()

    def _update_current_orders(self) -> None:
        """
        Remove any orders that are not open
        """
        # _logger.info(f'before update: {self._current_orders}')
        if any([not order.is_open() for order in self._current_orders]):
            self._current_orders = [order for order in self._current_orders if order.is_open()]
        # _logger.info(f'after update: {self._current_orders}')

    def run(self) -> BacktestResult:
        """Execute the strategy and return an immutable result snapshot."""
        stages: list[StageTelemetry] = []

        def measure(name: str, units: int, operation: Callable[[], Any]) -> None:
            elapsed_start = time.perf_counter()
            cpu_start = time.process_time()
            operation()
            stages.append(
                StageTelemetry(
                    name=name,
                    elapsed_seconds=time.perf_counter() - elapsed_start,
                    cpu_seconds=time.process_time() - cpu_start,
                    units=units,
                )
            )

        measure("validation", len(self.stage_graph().nodes), self.validate_stage_graph)
        measure("indicators", len(self.indicators) * len(self.contract_groups), self.run_indicators)
        measure("signals", len(self.signals) * len(self.contract_groups), self.run_signals)
        measure("rules_execution_accounting", len(self.timestamps), self.run_rules)
        analytics_count = len(self._risk_report_requests) + len(self._risk_result_requests)
        if analytics_count:
            measure("requested_analytics", analytics_count, self._run_requested_analytics)
        return self._backtest_result(tuple(stages))

    def _backtest_result(self, stages: tuple[StageTelemetry, ...]) -> BacktestResult:
        accepted = sum(decision.status is DecisionStatus.ACCEPTED for decision in self.order_decisions)
        rejected = len(self.order_decisions) - accepted
        filled = sum(order.status is OrderStatus.FILLED for order in self._orders)
        cancelled = sum(order.status is OrderStatus.CANCELLED for order in self._orders)
        open_orders = sum(order.is_open() for order in self._orders)
        telemetry = BacktestTelemetry(
            stages=stages,
            timestamps_processed=len(self.timestamps),
            orders_proposed=len(self._orders),
            orders_accepted=accepted,
            orders_rejected=rejected,
            orders_filled=filled,
            orders_cancelled=cancelled,
            orders_open=open_orders,
            trades_executed=self.account.trade_count,
        )
        orders = self.df_orders().with_columns(
            pl.Series("status", [order.status.name.lower() for order in self._orders], dtype=pl.String)
        )
        decisions = pl.DataFrame(
            {
                "symbol": [decision.order.contract.symbol for decision in self.order_decisions],
                "timestamp": np.asarray(
                    [decision.timestamp for decision in self.order_decisions], dtype="datetime64[ns]"
                ),
                "status": [decision.status.value for decision in self.order_decisions],
                "policy": [decision.policy for decision in self.order_decisions],
                "code": [decision.code for decision in self.order_decisions],
                "message": [decision.message for decision in self.order_decisions],
                "proposed_qty": [decision.proposed_qty for decision in self.order_decisions],
            },
            schema_overrides={
                "symbol": pl.String,
                "timestamp": pl.Datetime("ns"),
                "status": pl.String,
                "policy": pl.String,
                "code": pl.String,
                "message": pl.String,
                "proposed_qty": pl.Float64,
            },
        )
        risk_measures = _concat_artifact_frames(self._recorded_risk_results)
        risk_exposures = _concat_report_frames(self._recorded_risk_reports, "exposures")
        risk_attribution = _concat_report_frames(self._recorded_risk_reports, "attribution")
        stress_results = _concat_report_frames(self._recorded_risk_reports, "scenario_results")
        validation_rows: list[dict[str, object]] = []
        for name, report in sorted(self._recorded_validation_reports.items()):
            if not report.findings:
                validation_rows.append(
                    {
                        "artifact": name,
                        "is_valid": True,
                        "code": None,
                        "severity": None,
                        "message": None,
                        "count": 0,
                    }
                )
            for finding in report.findings:
                validation_rows.append(
                    {
                        "artifact": name,
                        "is_valid": report.is_valid,
                        "code": finding.code,
                        "severity": finding.severity.value,
                        "message": finding.message,
                        "count": finding.count,
                    }
                )
        validation_findings = pl.DataFrame(
            validation_rows,
            schema={
                "artifact": pl.String,
                "is_valid": pl.Boolean,
                "code": pl.String,
                "severity": pl.String,
                "message": pl.String,
                "count": pl.Int64,
            },
        )
        return BacktestResult(
            provenance=self.provenance,
            telemetry=telemetry,
            trades=self.df_trades(),
            orders=orders,
            decisions=decisions,
            pnl=self.df_pnl(),
            risk_measures=risk_measures,
            risk_exposures=risk_exposures,
            risk_attribution=risk_attribution,
            stress_results=stress_results,
            validation_findings=validation_findings,
        )

    def _get_orders(
        self, idx: int, rule_function: RuleType, contract_group: ContractGroup, params: dict[str, Any]
    ) -> list[Order]:
        try:
            indicator_values, signal_values, rule_name = (
                params["indicator_values"],
                params["signal_values"],
                params["rule_name"],
            )
            position_filter = self.position_filters[rule_name]

            if position_filter is not None:
                curr_pos = self.account.position(contract_group, cast(np.datetime64, self.timestamps[idx]))
                if position_filter == "zero" and not math.isclose(curr_pos, 0):
                    return []
                elif position_filter == "nonzero" and math.isclose(curr_pos, 0):
                    return []
                elif position_filter == "positive" and (curr_pos < 0 or math.isclose(curr_pos, 0)):
                    return []
                elif position_filter == "negative" and (curr_pos > 0 or math.isclose(curr_pos, 0)):
                    return []

            orders = validate_rule_orders(
                rule_function(
                    contract_group,
                    idx,
                    self.timestamps,
                    indicator_values,
                    signal_values,
                    self.account,
                    tuple(self._current_orders),
                    self.strategy_context,
                ),
                contract_group,
                self.timestamps[idx],
            )
        except Exception as exc:
            raise BacktestCallbackError(
                f"rule callback failed at index {idx} for contract group {contract_group.name}: {rule_function!r}"
            ) from exc
        return orders

    def _sim_market(self, i: int) -> None:
        """
        Go through all open orders and run market simulators to generate a list of trades and return any orders that were not filled.
        """
        for order in self._current_orders:
            idx = np.searchsorted(self.timestamps, order.timestamp)
            assert_(
                bool(idx >= 0 and idx < len(self.timestamps) and idx <= i),
                f"{i} {idx} {len(self.timestamps)} {order.timestamp}",
            )

            if (i - idx) < self.trade_lag:
                continue
            if (i - idx) > self.trade_lag:
                if order.time_in_force == TimeInForce.FOK:
                    order.cancel()
                    continue
            if order.status == OrderStatus.CANCEL_REQUESTED:
                order.cancel()

            if order.time_in_force == TimeInForce.DAY:
                if self.timestamps[i].astype("M8[D]") > order.timestamp.astype("M8[D]"):
                    order.cancel()

        for market_sim_function in self.market_sims:
            order_states: list[tuple[Order, float, OrderStatus]] = []
            try:
                self._update_current_orders()
                order_states = [(order, order.qty, order.status) for order in self._current_orders]
                current_orders = tuple(self._current_orders)

                trades = validate_market_trades(
                    market_sim_function(
                        current_orders,
                        i,
                        self.timestamps,
                        self.indicator_values,
                        self.signal_values,
                        self.strategy_context,
                    ),
                    current_orders,
                    self.timestamps[i],
                    {id(order): (qty, status) for order, qty, status in order_states},
                )
                for order, original_quantity, _status in order_states:
                    reported_fill = sum(trade.qty for trade in trades if trade.order is order)
                    if order.qty == original_quantity and reported_fill:
                        order.fill(reported_fill)

                if self.log_trades and len(trades) > 0:
                    if len(trades) > 1:
                        _logger.info("TRADES:" + "".join([f"\n {trade}" for trade in trades]))
                    else:
                        _logger.info(f"TRADE: {trades[0]}")

                if len(trades):
                    self.account.add_trades(trades)
            except Exception as exc:
                _restore_order_states(order_states)
                raise BacktestCallbackError(
                    f"market simulator failed at index {i}: {market_sim_function!r}"
                ) from exc
            except BaseException:  # order state must also roll back on cancellation and interpreter exit
                _restore_order_states(order_states)
                raise

        self._update_current_orders()

    def df_data(
        self,
        contract_groups: Sequence[ContractGroup] | None = None,
        add_pnl: bool = True,
        start_date: str | np.datetime64 = NAT,
        end_date: str | np.datetime64 = NAT,
    ) -> pl.DataFrame:
        """
        Add indicators and signals to market data and return a Polars DataFrame.

        Args:
            contract_groups (list of:obj:`ContractGroup`, optional): list of contract groups to include.  All if set to None (default)
            add_pnl: If True (default), include P&L columns in dataframe
            start_date: string or numpy datetime64. Default None
            end_date: string or numpy datetime64: Default None
        """
        _start_date, _end_date = np.datetime64(start_date), np.datetime64(end_date)
        if contract_groups is None:
            contract_groups = self.contract_groups

        timestamps = self.timestamps

        if not np.isnat(_start_date):
            timestamps = timestamps[timestamps >= _start_date]
        if not np.isnat(_end_date):
            timestamps = timestamps[timestamps <= _end_date]

        dfs = []

        for contract_group in contract_groups:
            mask = np.isin(self.timestamps, timestamps)
            df = pl.DataFrame({"timestamp": timestamps.astype("datetime64[ns]")})
            if add_pnl:
                df_pnl = self.df_pnl(contract_group)

            indicator_values = self.indicator_values[contract_group.name]

            for k in sorted(indicator_values.__dict__):
                name = k
                # Avoid name collisions
                if name in df.columns:
                    name = name + ".ind"
                df = df.with_columns(pl.Series(name, getattr(indicator_values, k)[mask]))

            signal_values = self.signal_values[contract_group.name]

            for k in sorted(signal_values.__dict__):
                name = k
                if name in df.columns:
                    name = name + ".sig"
                df = df.with_columns(pl.Series(name, getattr(signal_values, k)[mask]))

            if add_pnl:
                df = df.join(df_pnl, on="timestamp", how="left")
            # Add counter column for debugging
            df = df.with_columns(pl.Series("i", np.arange(len(df))))

            dfs.append(df)

        return pl.concat(dfs)

    def trades(
        self,
        contract_group: ContractGroup | None = None,
        start_date: np.datetime64 = NAT,
        end_date: np.datetime64 = NAT,
    ) -> list[Trade]:
        """Returns a list of trades with the given contract group and with trade date between (and including) start date
        and end date if they are specified.
        If contract_group is None trades for all contract_groups are returned"""
        return self.account.trades(contract_group, start_date, end_date)

    def roundtrip_trades(
        self,
        contract_group: ContractGroup | None = None,
        start_date: np.datetime64 = NAT,
        end_date: np.datetime64 = NAT,
    ) -> list[RoundTripTrade]:
        """Returns a list of trades with the given contract group and with trade date between (and including) start date
        and end date if they are specified.
        If contract_group is None trades for all contract_groups are returned"""
        return self.account.roundtrip_trades(contract_group, start_date, end_date)

    def df_trades(
        self,
        contract_group: ContractGroup | None = None,
        start_date: np.datetime64 = NAT,
        end_date: np.datetime64 = NAT,
    ) -> pl.DataFrame:
        """Returns a dataframe with data from trades with the given contract group and with trade date between (and including)
        start date and end date
        if they are specified. If contract_group is None trades for all contract_groups are returned"""
        return self.account.df_trades(contract_group, start_date, end_date)

    def df_roundtrip_trades(
        self,
        contract_group: ContractGroup | None = None,
        start_date: np.datetime64 = NAT,
        end_date: np.datetime64 = NAT,
    ) -> pl.DataFrame:
        """Returns a dataframe of round trip trades with the given contract group and with trade date
        between (and including) start date and end date if they are specified. If contract_group is None trades for all
        contract_groups are returned"""
        return self.account.df_roundtrip_trades(contract_group, start_date, end_date)

    def orders(
        self,
        contract_group: ContractGroup | None = None,
        start_date: np.datetime64 | str | None = None,
        end_date: np.datetime64 | str | None = None,
    ) -> list[Order]:
        """Returns a list of orders with the given contract group and with order date between (and including) start date and
        end date if they are specified.
        If contract_group is None orders for all contract_groups are returned"""
        orders: list[Order] = []
        _start_date = NAT if start_date is None else np.datetime64(start_date)
        _end_date = NAT if end_date is None else np.datetime64(end_date)
        if contract_group is None:
            orders += [
                order
                for order in self._orders
                if (np.isnat(_start_date) or np.datetime64(order.timestamp) >= _start_date)
                and (np.isnat(_end_date) or np.datetime64(order.timestamp) <= _end_date)
            ]
        else:
            for contract in contract_group.contracts.values():
                orders += [
                    order
                    for order in self._orders
                    if (contract is None or order.contract == contract)
                    and (np.isnat(_start_date) or np.datetime64(order.timestamp) >= _start_date)
                    and (np.isnat(_end_date) or np.datetime64(order.timestamp) <= _end_date)
                ]
        return [snapshot_order(order) for order in orders]

    def df_orders(
        self,
        contract_group: ContractGroup | None = None,
        start_date: np.datetime64 | str = NAT,
        end_date: np.datetime64 | str = NAT,
    ) -> pl.DataFrame:
        """Returns a dataframe with data from orders with the given contract group and with order date between (and including)
        start date and end date
        if they are specified. If contract_group is None orders for all contract_groups are returned"""
        orders = self.orders(contract_group, start_date, end_date)
        df_orders = pl.DataFrame(
            {
                "symbol": [order.contract.symbol if order.contract else "" for order in orders],
                "type": [type(order).__name__ for order in orders],
                "timestamp": np.asarray([order.timestamp for order in orders], dtype="datetime64[ns]"),
                "qty": np.asarray([order.qty for order in orders], dtype=float),
                "reason_code": [order.reason_code for order in orders],
                "order_props": [
                    str(order.properties.__dict__) if order.properties.__dict__ else "" for order in orders
                ],
                "contract_props": [
                    str(order.contract.properties.__dict__)
                    if order.contract and order.contract.properties.__dict__
                    else ""
                    for order in orders
                ],
            },
            schema_overrides={
                "symbol": pl.String,
                "type": pl.String,
                "timestamp": pl.Datetime("ns"),
                "qty": pl.Float64,
                "reason_code": pl.String,
                "order_props": pl.String,
                "contract_props": pl.String,
            },
        )
        return df_orders

    def df_pnl(self, contract_group=None) -> pl.DataFrame:
        """Returns a dataframe with P&L columns.  If contract group is set to None (default), sums up P&L across all contract groups"""
        return self.account.df_account_pnl(contract_group)

    def df_returns(self, contract_group: ContractGroup | None = None, sampling_frequency: str = "D") -> pl.DataFrame:
        """Return a dataframe of returns and equity indexed by date.

        Args:
            contract_group: The contract group to get returns for.
                If set to None (default), we return the sum of PNL for all contract groups
            sampling_frequency: Downsampling frequency.  Default is None.  See pandas frequency strings for possible values
        """
        from gambit.pq_utils import _polars_frequency

        pnl = self.df_pnl(contract_group).select("timestamp", "net_pnl", "equity").sort("timestamp")
        pnl = pnl.group_by_dynamic("timestamp", every=_polars_frequency(sampling_frequency)).agg(
            pl.col("net_pnl").last(), pl.col("equity").last()
        ).drop_nulls("equity")
        return pnl.with_columns(
            pl.when(pl.int_range(pl.len()) == 0)
            .then(pl.col("equity") / self.account.starting_equity - 1)
            .otherwise(pl.col("equity").pct_change())
            .alias("ret")
        )

    def evaluate_returns(
        self,
        contract_group: ContractGroup | None = None,
        periods_per_year: int = 0,
        plot: bool = True,
        display_summary: bool = True,
        float_precision: int = 4,
        return_metrics: bool = True,
    ) -> dict[str, Any] | None:
        """Computes return metrics and does or more of plotting, displaying or returning them.

        Args:
            contract_group (:obj:`ContractGroup`, optional): Contract group to evaluate or None (default) for all contract groups
            periods_per_year (int): If set to 0, we try to infer the frequency from the timestamps in the returns
                sometimes this is not possible, for example if you have daily returns with random gaps in the days
                In that case, you should set this value yourself. Use 252 if returns are on a daily frequency
            plot (bool): If set to True, display plots of equity, drawdowns and returns.  Default False
            float_precision (float, optional): Number of significant figures to show in returns.  Default 4
            return_metrics (bool, optional): If set, we return the computed metrics as a dictionary
        """
        returns = self.df_returns(contract_group)
        if returns.is_empty() or not bool(returns["ret"].is_not_null().any()):
            raise ValueError("return evaluation requires at least one return observation")
        metrics = self._reporter().metrics(
            returns["timestamp"].to_numpy(),
            returns["ret"].to_numpy(),
            self.account.starting_equity,
            periods_per_year=periods_per_year,
        )
        if display_summary:
            self._reporter().display(metrics, float_precision=float_precision)
        if plot:
            self._reporter().plot(metrics)
        if return_metrics:
            return metrics
        return None

    def plot_returns(self, contract_group: ContractGroup | None = None) -> Any:
        """Display plots of equity, drawdowns and returns for the given contract group or for all contract groups if contract_group
        is None (default)"""
        if contract_group is None:
            returns = self.df_returns()
        else:
            returns = self.df_returns(contract_group)

        if returns.is_empty() or not bool(returns["ret"].is_not_null().any()):
            raise ValueError("return plotting requires at least one return observation")

        metrics = self._reporter().metrics(
            returns["timestamp"].to_numpy(),
            returns["ret"].to_numpy(),
            self.account.starting_equity,
        )
        return self._reporter().plot(metrics)

    def _reporter(self) -> ReturnReporter:
        if self._return_reporter is None:
            from gambit.return_reporting import EvaluatorReturnReporter

            self._return_reporter = EvaluatorReturnReporter()
        return self._return_reporter

    def __repr__(self):
        return f"{pformat(self.indicators)} {pformat(self.rules)} {pformat(self.account)}"


if __name__ == "__main__":
    from test_strategy import test_strategy, test_strategy_2

    test_strategy()
    test_strategy_2()
    import doctest

    doctest.testmod(optionflags=doctest.NORMALIZE_WHITESPACE)
# $$_end_code
